### ISSUE TITLE
Question: what would the setup look like to simply copy the system highlights 

### ISSUE THREAD

**Issue by mblarsen** [rachartier/tiny-inline-diagnostic.nvim#1]
E.g. to use the same red on dark instead of the blended version on the right

<img width="795" alt="image" src="https://github.com/rachartier/tiny-inline-diagnostic.nvim/assets/247048/e7223d97-bbad-402d-9409-bf84343b62bf">

(ps I'm only showing both to be able to explain my questions)

**Comment by rachartier** [comment]
Hello!

You maybe need to tweak `hi.background` and set it to your current background color.
And by playing with `blend.factor`, you should be able to have the same colors as the left one.

But be careful of how you load your theme. You need to load your theme in first, before the plugin.

**Comment by mblarsen** [comment]
There is no option not to blend in case I just want to use my existing Highlights as is? (seems like a good default too)

**Comment by rachartier** [comment]
That's already what I do. I just take highlights from Diagnostic[Error,Warn,Info,Hint], and blend the background. 

So that's why you need to load the plugin after you made any change to these highlights !

**Comment by aimuzov** [comment]
@mblarsen, You can override setup highlight function:
```lua
require("tiny-inline-diagnostic.highlights").setup_highlights = function() end
```
and setup own highlights ([example](https://github.com/aimuzov/LazyVimx/commit/0296bf7210938ef1684abc3e1b9f23d53af992fd)).

Demo:

https://github.com/user-attachments/assets/b8323ce0-2a68-4889-8dea-8a5ab99be278

**Comment by rachartier** [comment]
@aimuzov beautiful neovim setup!

Thanks for the update. I hope it can help @mblarsen.
