### ISSUE TITLE
Plugin doesn't support multi-line errors

### ISSUE THREAD

**Issue by Shtsh** [rachartier/tiny-inline-diagnostic.nvim#10]
The plugin ignores `\n` in the diagnostic messages and shows everything on the same line

![Screenshot 2024-07-03 at 13 27 30](https://github.com/rachartier/tiny-inline-diagnostic.nvim/assets/602521/61795d12-410e-461c-a044-6f874f12122e)

It would be great if the pugin can display such messages properly to be readable.

**Comment by rachartier** [comment]
Hello,
Thanks for the feedback.
It should be good! Try to update it and tell me if it is good for you.

**Comment by Shtsh** [comment]
Thank you. The new line is now respected. However I see the issue that the plugin probably doesn't take in account inlay hints and the new line seems to be shifted.
<img width="1721" alt="Screenshot 2024-07-04 at 13 05 18" src="https://github.com/rachartier/tiny-inline-diagnostic.nvim/assets/602521/8c4466f6-b6e9-448b-bed1-e2556945a9bc">

**Comment by rachartier** [comment]
Yes... I don't really know how to handle this for now. It's the same with `ghost_text` for nvim-cmp. I need to do more testing to handle this problem :(
