### ISSUE TITLE
feat: show all errors on every line

### ISSUE THREAD

**Issue by ilan-schemoul** [rachartier/tiny-inline-diagnostic.nvim#11]
With the default LSP diagnostic virtual_text option we can see the virtual_text on every lines where there is a mistake.
I would like the same thing on this plugin.
I do not use symbol column as I like things minimal (I also prefer no statusline etc.) therefore I really need virtual_text everywhere

**Comment by rachartier** [comment]
Hello!

I know it's something that could be useful, but it also completely defeats the plugin's purpose, as it is meant to only show what the diagnostic under the cursor is, to reduce noise and too much feedback. So, I'm very mitigated about it...

**Comment by BrunoKrugel** [comment]
> Hello!
> 
> I know it's something that could be useful, but it also completely defeats the plugin's purpose, as it is meant to only show what the diagnostic under the cursor is, to reduce noise and too much feedback. So, I'm very mitigated about it...

Maybe add a optional opts? Or a new plugin maybe 🤔

**Comment by ilan-schemoul** [comment]
> Hello!
> 
> I know it's something that could be useful, but it also completely defeats the plugin's purpose, as it is meant to only show what the diagnostic under the cursor is, to reduce noise and too much feedback. So, I'm very mitigated about it...

I am not interested in only having one error displayed.
I find the design of the errors/warnings appealing. Posts on Reddit also describe the main interest of this plugins as being prettier than vanilla warning/errors

If it can be made optional what's the harm ? If you're not willing to code it lmk if you would accept a PR

**Comment by rachartier** [comment]
Yes you can try, but since the code was neither designed nor optimized for this use, it is quite difficult to implement!

**Comment by sontungexpt** [comment]
> With the default LSP diagnostic virtual_text option we can see the virtual_text on every lines where there is a mistake. I would like the same thing on this plugin. I do not use symbol column as I like things minimal (I also prefer no statusline etc.) therefore I really need virtual_text everywhere

If you like, you can try my plugin [better-diagnostic-virtual-text](https://github.com/sontungexpt/better-diagnostic-virtual-text). Please note that as a student, there may be periods when I am unable to maintain it due to my academic commitments. Additionally, the plugin is designed to work with my personal theme and does not support built-in highlighting like tiny-diagnostic.nvim. You may need to write some custom code to enhance your experience. I'm not like all diagnostics so may be it had some bugs.

**Comment by rachartier** [comment]
> > With the default LSP diagnostic virtual_text option we can see the virtual_text on every lines where there is a mistake. I would like the same thing on this plugin. I do not use symbol column as I like things minimal (I also prefer no statusline etc.) therefore I really need virtual_text everywhere
> 
> If you like, you can try my plugin [better-diagnostic-virtual-text](https://github.com/sontungexpt/better-diagnostic-virtual-text). Please note that as a student, there may be periods when I am unable to maintain it due to my academic commitments. Additionally, the plugin is designed to work with my personal theme and does not support built-in highlighting like tiny-diagnostic.nvim. You may need to write some custom code to enhance your experience. I'm not like all diagnostics so may be it had some bugs.

That's... something I haven't seen yet, to promote your own work on an issue.

**Comment by sontungexpt** [comment]
> > > With the default LSP diagnostic virtual_text option we can see the virtual_text on every lines where there is a mistake. I would like the same thing on this plugin. I do not use symbol column as I like things minimal (I also prefer no statusline etc.) therefore I really need virtual_text everywhere
> > 
> > 
> > If you like, you can try my plugin [better-diagnostic-virtual-text](https://github.com/sontungexpt/better-diagnostic-virtual-text). Please note that as a student, there may be periods when I am unable to maintain it due to my academic commitments. Additionally, the plugin is designed to work with my personal theme and does not support built-in highlighting like tiny-diagnostic.nvim. You may need to write some custom code to enhance your experience. I'm not like all diagnostics so may be it had some bugs.
> 
> That's... something I haven't seen yet, to promote your own work on an issue.
ah I'm a bit hesitant about publishing my plugin in an issue of another project, so I wrote it down a bit

**Comment by rachartier** [comment]
Hi again.

I've finally succeeded to implement multilines diagnostics.
Example:

![image](https://github.com/user-attachments/assets/2741ff16-76d0-452d-870d-66e3c320108a)

It'll probably need more tweaking, but the core principle is done.

**Comment by rachartier** [comment]
You can enable it like so:
```lua
opts = {
    options = {
        multilines = true,
    }
}
```

**Comment by ilan-schemoul** [comment]
Yes, it works flawlessly. Thanks a lot !

**Comment by rachartier** [comment]
Do not hesitate to comment on the issue if you find anything.

Thank you !
