### ISSUE TITLE
Diagnostic Line Issue: Temporary Line Causes Line Shift

### ISSUE THREAD

**Issue by SourishBiswas23** [rachartier/tiny-inline-diagnostic.nvim#14]
I noticed that if I go to a line with diagnostics, the plugin creates another empty line below the current line, which causes the lines under it to shift downwards. The temporary line is present for the duration of the fix. Once it is fixed or once I go to another line, the line is gone. This happens when the diagnostic message is long and is rendered in a rectangle. The video is attached with this description.

https://github.com/rachartier/tiny-inline-diagnostic.nvim/assets/108509673/8cb8d79c-3a16-44d7-978f-191b19dd4960

**Comment by rachartier** [comment]
Thanks for creating an issue here.

But I'm sorry, I can't really see what's wrong ?
You do not want the wrapped diagnostic ? If so you can set `overflow = "none"` in the setup.

**Comment by SourishBiswas23** [comment]
I am sorry for the confusion. The problem is that when I am working code that is already written, the plugin inserts new temporary lines below the current line( if the diagnostic message is long enough), which causes the lines below it to shift downwards. After the problem gets fixed, the temporary line disappears, causing the lines to shift upwards to their usual position. This frequent shift of lines causes strain in the eyes. There is no such problem in writing new code as there are no lines to shift.

The feature I am asking for is one where the diagnostic message overlays on top of the code like nvim-cmp.

**Comment by rachartier** [comment]
Hello again,

I've added your suggestion, and made it default, because I really think it's nicer this way!
You can update and tell me if it is good for you.

Thank you !

**Comment by SourishBiswas23** [comment]
Hello,

Thank you so much for implementing my suggestion and making it the default! I’ve updated the plugin and it’s working perfectly. I really appreciate your quick response and effort.

Thanks again!
