### ISSUE TITLE
Conflict with git-blame

### ISSUE THREAD

**Issue by patrick91** [rachartier/tiny-inline-diagnostic.nvim#16]
https://github.com/f-person/git-blame.nvim

I really like this plugin, but do you know if there's a way to make this play nice with git blame? 😊

https://github.com/rachartier/tiny-inline-diagnostic.nvim/assets/667029/e8ab8616-0753-412d-9845-4313373d9e45

**Comment by rachartier** [comment]
Hello! Thank you very much.

In fact, that's a recurring problem with other "virtual text" plugins, like nvim-cmp. I haven't found a solution yet, but I'm working on it. I'll get back to you if I make any progress !

**Comment by kidp2h** [comment]
![image](https://github.com/rachartier/tiny-inline-diagnostic.nvim/assets/40386174/96f1a72a-50a1-4142-96cd-e2a80c3cc515)

for the temporary fix, you can set mode extmark  to eol in your config
`options = {
    overflow = {
        position = "eol"
}`

It works for me :)

**Comment by rachartier** [comment]
Oh... nice catch !

**Comment by daUnknownCoder** [comment]
> `options = { overflow = { position = "eol" }`

works for me but its reversed, i use gitsigns.nvim for the blame, but my blame comes before inline diag idk why

**Comment by patrick91** [comment]
@kidp2h where should I put this configuration? :D

**Comment by rachartier** [comment]
Hello,

Thank you all for your feedbacks.
I've modified the code to handle others extmarks like:

- `nvim-cmp` (ghost text)
- `gitblame`
- `Copilot`
And others...

You can also remove the workaround @kidp2h found. You now cannot set `eol` or `overlay` anymore, it's a mix between the two!

The thing is, it's hard to catch all the small details! So please, can you try to change your branch to `branch = 16-conflict-with-git-blame`, and then give me a feedback ?

Thank a lot again.

**Comment by daUnknownCoder** [comment]
yo, codeium.vim also produces ghost text, ill try asap

**Comment by rachartier** [comment]
Do you use the same gitblame plugin as Patrick91 ? "f-person/git-blame.nvim" ?

**Comment by kidp2h** [comment]
> ![image](https://private-user-images.githubusercontent.com/84800625/347410950-8a27de6c-8d51-4f7c-98a0-f8b503eb6bbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTc0MDIsIm5iZiI6MTcyMDYxNzEwMiwicGF0aCI6Ii84NDgwMDYyNS8zNDc0MTA5NTAtOGEyN2RlNmMtOGQ1MS00ZjdjLTk4YTAtZjhiNTAzZWI2YmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDEzMTE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhZDdkMTg3M2JkZTYwZTA2MmZlODUyNDcyODI3Yjk0NTQ3Y2RiMTBkYmUxNGNhMThlMjc2MzZjNTJhMzUzNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pXc_tkOxh2s6EFtA-Yvx_CyzDr0bYY-yHcy-vZNM6HI)
> 
> idk why but gitsigns blame has more priority over the diagnostic also needed an option for _not updating in insert mode (its annoying fr)_
> 
> and ![image](https://private-user-images.githubusercontent.com/84800625/347411743-b47609bd-7749-44dc-9f07-13c918529677.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTc0MDIsIm5iZiI6MTcyMDYxNzEwMiwicGF0aCI6Ii84NDgwMDYyNS8zNDc0MTE3NDMtYjQ3NjA5YmQtNzc0OS00NGRjLTlmMDctMTNjOTE4NTI5Njc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDEzMTE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5MzU2ZGM1YmZkZjY1Mjg2ODhhODA5NDU5ZDYxZWU1Yzg0YWQ3YWFlYjYyYmJkODA5NjVhMDk1MGMyMjdkOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x0QdAb-wDRloazs71S0mvuhykUrl-fLu8jND8UB64e8)
> 
> codeium.vim ghost text makes it miserable

IMO, we should remove virtual text when inserting mode

**Comment by rachartier** [comment]
Yep you're right. That's what I did in the first version... It'll be far easier to maintain this way. I've pushed the fix.

**Comment by kidp2h** [comment]
> Do you use the same gitblame plugin as Patrick91 ? "f-person/git-blame.nvim" ?

I think that plugin is this: https://github.com/lewis6991/gitsigns.nvim

I tried
![image](https://github.com/rachartier/tiny-inline-diagnostic.nvim/assets/40386174/07c8835c-0192-4ee9-a86e-e10f95380b95)

That'll be good when we set virt_text_priority higher than diagnostic in gitsigns config
`current_line_blame_opts.virt_text_priority = 2049`

**Comment by rachartier** [comment]
Nice catch. I've added an option to set the priority, I don't want others to have to modify their existing configuration for the plugin to work !

```lua
{
     virt_texts = {
          priority = 2048,
     }
}
```

**Comment by daUnknownCoder** [comment]
> Do you use the same gitblame plugin as Patrick91 ? "f-person/git-blame.nvim" ?

no i use gitsigns in-built blame : https://github.com/lewis6991/gitsigns.nvim?tab=readme-ov-file
