### ISSUE TITLE
Multiple diagnostics under cursor

### ISSUE THREAD

**Issue by lostl1ght** [rachartier/tiny-inline-diagnostic.nvim#17]
Hi!

Sometimes there are multiple diagnostics under cursor. Consider this example in rust:

```rust
fn main() {
    println!("Hello, world!;
}
```

If you put your cursor one the last curly brace the plugin displays only the first diagnostic.
But there are actually 4 diagnostics there:

![image](https://github.com/rachartier/tiny-inline-diagnostic.nvim/assets/61948252/f368c7e6-62c7-4450-ac41-3ae321165573)

Is it possible to have them all displayed?

**Comment by rachartier** [comment]
Hello! Thanks for the feedback.

I've added `options.multiple_diag_under_cursor` to do that. You need to set it to true, as it is not by default.

Tell me if it is good for you !

**Comment by rachartier** [comment]
That was on purpose, I thought it rendered better. But I can add the lest separator, I don't know...

**Comment by rachartier** [comment]
Hello, sorry for the delay.

I've added what you said, but kept the first '(' and last ')'. 

```
(  *  Wrapped         |
 | |  diagnostic      |
 | |  message         |
 | |_ very wrapped    |
 | *  Another         |
 | |_ message         |
 | * Not wrapped       )
```

Thanks !
