### ISSUE TITLE
Problems with tokyonight-day

### ISSUE THREAD

**Issue by strayer** [rachartier/tiny-inline-diagnostic.nvim#18]
I'm facing issues using this plugin with tokyonight-day:

<img width="741" alt="58648" src="https://github.com/rachartier/tiny-inline-diagnostic.nvim/assets/310624/ecb976ef-35b6-464b-8fe6-9810c4973810">

<img width="666" alt="40267" src="https://github.com/rachartier/tiny-inline-diagnostic.nvim/assets/310624/b001bd0d-89b7-44d2-a594-d312cf934736">

`vim.o.background` is `light`, I'm using the default settings for the plugin:

```
  {
    "rachartier/tiny-inline-diagnostic.nvim",
    event = "VeryLazy",
    config = function()
      vim.diagnostic.config({ virtual_text = false })
      require("tiny-inline-diagnostic").setup()
    end,
  },
```

Is it supposed to look like this? The very dark background makes reading the diagnostic messages pretty hard and look very off compared to the rest of the colorscheme.

**Comment by rachartier** [comment]
Hello,

You can adjust `blend.factor` and `hi.mixin_color` to get a better result. 
Try to reduce `blend.factor` first, then play with some shade of gray for `hi.mixin_color`, like `#e7e7e7`, `#aaaaaa` ...

**Comment by rachartier** [comment]
And are you sure that you set vim.o.background to light before the plugin setup ?

**Comment by strayer** [comment]
Just to be safe I changed the plugin configuration like this:

```lua
  {
    "rachartier/tiny-inline-diagnostic.nvim",
    event = "VeryLazy",
    config = function()
      vim.o.background = "light"
      vim.diagnostic.config({ virtual_text = false })
      require("tiny-inline-diagnostic").setup()
    end,
  }
```

This should make sure that the background was set correctly, didn't change anything though.

I did play around with the colors as you suggested and it is _much_ more readable now:

<img width="648" alt="grafik" src="https://github.com/user-attachments/assets/89f36d4d-d376-43f6-8d56-18ce4fed7e24">
<img width="574" alt="grafik" src="https://github.com/user-attachments/assets/0a101880-71bd-4d8b-a7b3-874e2ceb1921">
<img width="688" alt="grafik" src="https://github.com/user-attachments/assets/3f34d3e6-451e-4716-a153-fb733252047a">

Full config:

```lua
  {
    "rachartier/tiny-inline-diagnostic.nvim",
    event = "VeryLazy",
    config = function()
      vim.diagnostic.config({ virtual_text = false })
      require("tiny-inline-diagnostic").setup({
        hi = {
          mixing_color = "#e7e7e7"
        },
        blend = {
          factor = 0.27
        }
      })
    end,
  }
```

I'm bad with colors so I have now idea what is happening here, but it looks great, so I'm happy :)

**Comment by strayer** [comment]
The only other issue I'm running into in this context now is that I'm dynamically switching `vim.o.background` based on my OS. I need to reload the plugin with different configurations in that situation because this mixing_color only works in the day theme. I tried using the change function, but I don't think that handles the mixing_color well. Any tips on how to update the configuration in running neovim instances?

**Comment by rachartier** [comment]
Hello, yes that looks really nice with these colors !

If you call setup more than once, then all autocmd inside the plugin will be recreated.
So I've added a new update, where you can what you did ! It will now not recreate the autocmds, so all should be good.

**Comment by rachartier** [comment]
That's strange... ! I will look into it

**Comment by rachartier** [comment]
Ah... I'm sorry. I forgot that I had added `change` method to do exactly that !

You can look in the first entry in the API section here: https://github.com/rachartier/tiny-inline-diagnostic.nvim?tab=readme-ov-file#-api

**Comment by strayer** [comment]
I tried that earlier, but I need to change the mixing_color, not the background. I think the change function doesn't help me there, right?

This is the part that differs based on light or dark background:

```lua
      hi = {
        mixing_color = vim.o.background == "light" and "#e7e7e7" or "None",
      },
```

**Comment by rachartier** [comment]
You're right,
I've modified the `change` method. It now takes two table: blend and highliths (the same as the setup). It should work!

Sorry for all the problems...

**Comment by strayer** [comment]
No need to apologize! I'm very grateful for you building this plugin and supporting my specific usecase! It seems to work great now. For future reference, this is how I'm configuring the plugin:

```lua
-- lua/config-tiny-inline-diagnostics.lua
local function cfg_values()
  return {
    mixing_color = vim.o.background == "light" and "#e7e7e7" or "None",
    blend_factor = 0.27,
  }
end

local function cfg()
  vim.diagnostic.config({ virtual_text = false })

  local values = cfg_values()

  require("tiny-inline-diagnostic").setup({
    hi = {
      mixing_color = values.mixing_color,
    },
    blend = {
      factor = values.blend_factor,
    },
  })
end

local function change()
  local values = cfg_values()
  require("tiny-inline-diagnostic").change({
    factor = values.blend_factor,
  }, {
    mixing_color = values.mixing_color,
  })
end

return {
  cfg = cfg,
  change = change,
}
```

```lua
-- lua/plugins.lua

-- [...]
  {
    "rachartier/tiny-inline-diagnostic.nvim",
    event = "VeryLazy",
    config = require("config-tiny-inline-diagnostic").cfg,
  },
-- [...]
```

And this is the code that is run when my OS theme changes:

```lua
local set_from_os = function()
  if os_is_dark() then
    vim.o.background = "dark"
  else
    vim.o.background = "light"
  end

  if package.loaded['tiny-inline-diagnostic'] then
    require("config-tiny-inline-diagnostic").change()
  end

  -- reconfigure lualine to load correct theme
  if package.loaded['lualine'] then
    require("config-lualine").cfg()
  end
end
```

**Comment by rachartier** [comment]
Looks nice ! Thank you very much, have a nice day
