### ISSUE TITLE
Delay in insert mode

### ISSUE THREAD

**Issue by arielherself** [rachartier/tiny-inline-diagnostic.nvim#2]
Not sure if it's caused by my other configurations, after typing a character the inline text seems to show the diagnostics of previous state.

Here is a screenshot showing it:

![image](https://github.com/rachartier/tiny-inline-diagnostic.nvim/assets/107245128/dba4c528-a782-498a-8d34-c4c9f07c9409)

As you can see, it is `jj` instead of `jjj`.

**Comment by rachartier** [comment]
Hello, thanks for using the plugin.

Yes, it's probably because the LSP hasn't updated itself yet. My plugin is based on vim.diagnostic, so if the LSP doesn't trigger an update, I can't really catch it...

It greatly depends on the LSP. I have the same problem with Lua and Python.

**Comment by arielherself** [comment]
Oh I understand. And thanks for your awesome plugin!
