### ISSUE TITLE
Invalid Buffer ID

### ISSUE THREAD

**Issue by tuckerbeauchamp** [rachartier/tiny-inline-diagnostic.nvim#20]
I'm using this plugin on two machines.

Mac - Kitty
Windows (WSL) - Default windows terminal

Mac works fine. However on the WSL system it seems to have an issue when I try to save any Oil buffer. 

`Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/diagnostic.lua:352: Invalid buffer id: 1`

It looks like the buffer that gets passed to `get_diagnostic_under_cursor()` is invalid for some reason inside of Oil. 

I have fixed the issue by checking for a valid buffer before calling `vim.diagnostic.get()`

```lua
--- Function to get the diagnostic under the cursor.
--- @param buf number - The buffer number to get the diagnostics for.
--- @return table, number, number - A table of diagnostics for the current position, the current line number, the current col, or nil if there are no diagnostics.
function M.get_diagnostic_under_cursor(buf)
	local cursor_pos = vim.api.nvim_win_get_cursor(0)
	local curline = cursor_pos[1] - 1
	local curcol = cursor_pos[2]

	--- Check if the buffer is valid
	if not vim.api.nvim_buf_is_valid(buf) then
		return
	end

	local diagnostics = vim.diagnostic.get(buf, { lnum = curline })

	if #diagnostics == 0 then
		return
	end

	return get_current_pos_diags(diagnostics, curline, curcol), curline, curcol
end
```

I could submit a PR if you would like. I've never worked with lua (outside of neovim) so I'm not sure if this is the ideal fix.

Let me know!

P.S. Awesome plugin man, really enjoying it

**Comment by rachartier** [comment]
Thank you very much !

I'll look at it tomorrow. You'll be informed when this is fixed !

**Comment by rachartier** [comment]
That should be fixed. Tell me if it is good for you!
