### ISSUE TITLE
Plugin doesn't work in nvim <= 0.9.5

### ISSUE THREAD

**Issue by KostkaBrukowa** [rachartier/tiny-inline-diagnostic.nvim#22]
Option `overlap` in `nvim_buf_get_extmarks` was added in nvim 0.10 according to https://neovim.io/doc/user/news-0.10.html
https://github.com/rachartier/tiny-inline-diagnostic.nvim/blob/main/lua/tiny-inline-diagnostic/extmarks.lua#L19
I guess this should be mentioned in the Readme or handled in the code

Btw great plugin!!

**Comment by rachartier** [comment]
Oh thanks! I will add it to the README.
