### ISSUE TITLE
feat: mappings to jump next and prev diagnostics

### ISSUE THREAD

**Issue by basilgood** [rachartier/tiny-inline-diagnostic.nvim#23]
Thanks for your work. :heart: 
Jumping diagnosticks with `]d` and `[d` it show the default neovim diagnostic and tiny-inline.
I wonder if is possible to have some mappings to jump only to tiny diagnostics.

**Comment by rachartier** [comment]
Hello, thank you !

That's strange, I don't have the same issue...

![tinyinlinediagnostic_gn_gp](https://github.com/user-attachments/assets/d4a4a4d5-a382-4f4c-9209-bce7e1e1c560)

Are you sure that you have correctly set `vim.diagnostic.config({ virtual_text = false })` ?

**Comment by basilgood** [comment]
Sorry!!! I had this mappings 
`  vim.keymap.set('n', '[d', vim.diagnostic.goto_prev)  vim.keymap.set('n', ']d', vim.diagnostic.goto_next)` 
after tiny-inline plugin.
  Yes it works well.
 If you don't mind, how did you get the virtual text to be without line background ?
 This is mine with catppuccin:
 
![image](https://github.com/user-attachments/assets/d948dec5-f576-43b9-b9d0-4bf23caea61f)

**Comment by rachartier** [comment]
Nice!

You just need to set `CursorLine` to `None`. You could do like so: `vim.api.nvim_set_hl(0, "CursorLine", { bg = "None"})`
Or inside `catpuccin` directly:

```lua
require("catppuccin").setup {
    --- Your config...
    custom_highlights = function(colors)
        return {
            CursorLine = { bg = "None" },
        }
    end
}
```

**Comment by basilgood** [comment]
Sorry, boterring you again.
That cursorline appears because you set it here:
 https://github.com/rachartier/tiny-inline-diagnostic.nvim/blob/4b5bc565d8ea4dce4bc45bba57f292578ba5197c/lua/tiny-inline-diagnostic/extmarks.lua#L74
 https://github.com/rachartier/tiny-inline-diagnostic.nvim/blob/4b5bc565d8ea4dce4bc45bba57f292578ba5197c/lua/tiny-inline-diagnostic/extmarks.lua#L100
 https://github.com/rachartier/tiny-inline-diagnostic.nvim/blob/4b5bc565d8ea4dce4bc45bba57f292578ba5197c/lua/tiny-inline-diagnostic/extmarks.lua#L111
 
It's not necessary to set it.
It's an optional parameter for nvim_buf_set_extmark.
I tried and completely deleted that line from the 3 places and now it works perfectly without cursorline.
So there is no need to change the colorscheme and put Cursorline guibg=NONE.
If you consider it necessary, it can be optionally added for those who want a cursorline for diagnostics.

**Comment by rachartier** [comment]
Hello,

Yes, it will work without it, but for someone who have a background on his cursorline, it will not. That's why I link CursorLine to `line_hl_group`, so that it can works for both.

When you say:
> I tried and completely deleted that line from the 3 places and now it works perfectly without cursorline

Does it not work for you if CursorLine is in `line_hl_group`? If so I could look at it.

**Comment by basilgood** [comment]
>Does it not work for you if CursorLine is in line_hl_group?

Yes, it's not work for me, but it seems it doesn't work for you either because you need to tweak colorscheme.
i tried several color schemes tokyonight, kanagawa, etc and now with catppuccin it's the same I have a cursorline because of line_hl_group. That's why I proposed to make `line_hl_group` optional and have it in setup options.
Thanks for your patience.
