### ISSUE TITLE
Show source of error

### ISSUE THREAD

**Issue by patrick91** [rachartier/tiny-inline-diagnostic.nvim#24]
Hi there, is it possible to show where an error is coming from, I have issues like this one:

<img width="753" alt="image" src="https://github.com/user-attachments/assets/f2c7e9ac-f8a3-4403-b81a-7457bd7fd5f6">

but I'm struggling to figure where they come from

**Comment by rachartier** [comment]
Hello! Thank you for your feedback.

I've added this as an option (not enabled by default): 
```lua 
{
    options = {
        show_source = true
    }
}
```
