### ISSUE TITLE
diagnostic are not showing up in lua_ls projects

### ISSUE THREAD

**Issue by s1n7ax** [rachartier/tiny-inline-diagnostic.nvim#25]
Diagnostics are not showing up with lua_ls. I never encountered this issue with native diagnostic popup and I'm only seeing this on lua_ls projects. It's not always either.

In the following video, on jump, tiny-inline-diagnostic supposed to show the error but it does not. When I run <leader>cd which is the shortcut to native popup, it works. Sometimes when the buffer is reloaded with `e!` it starts working.

https://github.com/user-attachments/assets/12f64fe9-2743-4715-aad0-311f27d42332

**Comment by rachartier** [comment]
How do you load the plugin ?
I intercept the "LspAttach" autocmd, so if you load it after, it will not work.

**Comment by s1n7ax** [comment]
Forgot the config.

```lua
return {
	'rachartier/tiny-inline-diagnostic.nvim',
	event = 'LspAttach',
	keys = {
		{
			']d',
			function()
				vim.diagnostic.jump({ float = false, count = 1 })
			end,
			desc = 'Next Diagnostic',
		},

		{
			'[d',
			function()
				vim.diagnostic.jump({ float = false, count = -1 })
			end,
			desc = 'Prev Diagnostic',
		},
	},
	opts = function(_, opts)
		vim.diagnostic.config({ virtual_text = false })
		return opts
	end,
}

```

**Comment by rachartier** [comment]
Can you try to set `event` to `VeryLazy` ? And tell me then if it is better ?

**Comment by s1n7ax** [comment]
Ahh. that's unrelated! <c-c> for some reason does not update the diagnostics. I removed the <esc> mapping after a treesitter fix recently got merged.
 
https://www.reddit.com/r/neovim/comments/1aobbv7/solved_neovim_lsp_inline_diagnostics_not_showing/

**Comment by s1n7ax** [comment]
Hold on, don't close. there is an some kind of issue. I'll debug.

**Comment by s1n7ax** [comment]
You are correct. It's the 'LspAttach' being executed before plugin is loaded, at the same time I had the <c-c> issue.
