### ISSUE TITLE
Broken highlighting

### ISSUE THREAD

**Issue by dsully** [rachartier/tiny-inline-diagnostic.nvim#26]
![CleanShot 2024-08-07 at 05 52 28@2x](https://github.com/user-attachments/assets/0366f7b0-2eca-47ba-bb3a-f6d9a5fb59d4)

I'm not sure where the lighter gray is coming from - it seems like a rendering bug?

Here's my config:

```lua
    {
        "rachartier/tiny-inline-diagnostic.nvim",
        event = "LspAttach",
        init = function()
            vim.diagnostic.config({ virtual_text = false })
        end,
        opts = {
            hi = {
                background = require("config.defaults").colors.black.dim,
            },
            options = {
                multiple_diag_under_cursor = true,
                show_source = true,
                throttle = 0,
            },
            signs = {
                left = "",
                right = "",
            },
        },
    },
```

Additionally, I'd like to have the diagnostic highlight be both a foreground and background I set without any blending.

Looking at the code base that isn't possible today. I tried setting `TinyInlineDiagnosticVirtualTextError` (and others) explicitly, but they are overwritten in `M.setup_highlights`

Thanks

**Comment by dsully** [comment]
Ok - fixed the rendering part by setting:

```lua
CursorLine = { bg = "None" },
```

**Comment by rachartier** [comment]
Can you give me a minimal code example that can reproduce this bug, please? I cannot seem to reproduce it with Lua or Python.

**Comment by dsully** [comment]
Clone https://github.com/dsully/zoned 

Then comment out line 89, which will trigger the diagnostic (as shown above in the video).

You'll need `rust-analyzer` setup of course.

**Comment by rachartier** [comment]
Should be good. Can you update and test please?

**Comment by dsully** [comment]
Better, thank you.

How can I control the amount of padding the diagnostic block uses?

![CleanShot 2024-08-08 at 07 28 09@2x](https://github.com/user-attachments/assets/dc177529-2b4f-488c-908f-f0b92e7e8256)

**Comment by rachartier** [comment]
I think you should do:

```lua
            signs = {
                left = " ",
                right = " ",
            },
```
