### ISSUE TITLE
new line shows as `^@`

### ISSUE THREAD

**Issue by RayGuo-ergou** [rachartier/tiny-inline-diagnostic.nvim#27]
Hi, in typescript the message is very common to have empty lines, and the new line will show as `^@` see screen short below.

![image](https://github.com/user-attachments/assets/a1695df4-b0fa-4a5e-ab74-953dd3045d40)

**Comment by RayGuo-ergou** [comment]
ps: only happen set overflow mode to `none`

**Comment by RayGuo-ergou** [comment]
Did a briefly look and this will fix my issue, this is pretty simple as I don't have much understand of the codebase but hope can help :)

```diff
diff --git a/lua/tiny-inline-diagnostic/chunk.lua b/lua/tiny-inline-diagnostic/chunk.lua
index 058d393..d28acf0 100644
--- a/lua/tiny-inline-diagnostic/chunk.lua
+++ b/lua/tiny-inline-diagnostic/chunk.lua
@@ -217,6 +217,10 @@ function M.get_chunks(opts, diag, plugin_offset, curline, buf)
 		chunks = { " " .. diag.message }
 	end
 
+	for i, chunk in ipairs(chunks) do
+		chunks[i] = string.gsub(chunk, "\n", " ")
+	end
+
 	return {
 		chunks = chunks,
 		severity = diag.severity,
```

**Comment by rachartier** [comment]
Hello! Thanks for the feedback.

I've fixed the issue. It will now correctly parse a "new line" character.
Can you test the latest commit and tell me if it's all good? Thanks !

**Comment by RayGuo-ergou** [comment]
Thanks! The symbol issue is fixed. However, Could I have one more request? Currently if the diagnostic message is multiple line even tho I set the overflow to none it will still be multi lines. Can we mimic what native neovim lsp behaviour which is no matter how many line in diagnostic message the virtual message is always one line. Or could you add one more config option that allow user modify the text.

**Comment by rachartier** [comment]
Sorry, I misunderstood your issue the first time.

It is now done. You can set `overflow.mode` to `oneline` and it should be ok !

**Comment by RayGuo-ergou** [comment]
> Sorry, I misunderstood your issue the first time.

I was not making that clear kinda on me haha.

![image](https://github.com/user-attachments/assets/860ceed8-7edb-42c0-bb65-0d10649558ca)

And it look perfect to me now, thank you very much 🥳.

And just a reminder, the debug code is still left in the codebase 😉

```diff
diff --git a/lua/tiny-inline-diagnostic/chunk.lua b/lua/tiny-inline-diagnostic/chunk.lua
index 2b0193f..38f7125 100644
--- a/lua/tiny-inline-diagnostic/chunk.lua
+++ b/lua/tiny-inline-diagnostic/chunk.lua
@@ -213,8 +213,7 @@ function M.get_chunks(opts, diag, plugin_offset, curline, buf)
 		elseif opts.options.overflow.mode == "none" then
 			chunks = utils.wrap_text(diag.message, 0)
 		elseif opts.options.overflow.mode == "oneline" then
-			print(utils.remove_newline(diag.message .. "\ncoucou\ncoucu\n\nazeaz"))
-			chunks = { utils.remove_newline(diag.message .. "\ncoucou\ncoucu\n\nazeaz") }
+			chunks = { utils.remove_newline(diag.message) }
 		end
 	else
 		chunks = { " " .. diag.message }
```

**Comment by RayGuo-ergou** [comment]
Created a PR for it #28 😁

**Comment by rachartier** [comment]
Omg... sorry, thank you very much !!

**Comment by RayGuo-ergou** [comment]
haha it's all good, we all push debug code sometimes.

I also want to say thank you for this amazing plugin, it saved me so much "mental engage" so I can focus more on the code!💖

**Comment by rachartier** [comment]
That's nice to hear! Thanks a lot !!
