### ISSUE TITLE
[FR]support format

### ISSUE THREAD

**Issue by jiz4oh** [rachartier/tiny-inline-diagnostic.nvim#29]
Hi @rachartier, could you consider adding the format options that let customers customize the diagnostic message as same as the built-in `vim.diagnostic.config()`

![image](https://github.com/user-attachments/assets/d4711cdd-848b-414f-87e9-3fe479a09b37)

**Comment by rachartier** [comment]
Hello,

It is done. You can define a `format` function in `opts.options.format`. It takes `vim.Diagnostic` as an input, and return a `string`.

**Comment by jiz4oh** [comment]
thank you for your quick action!!!

**Comment by jiz4oh** [comment]
Hi @rachartier, sorry to bother you again, I found the `format` function is not working if [opts.options.overflow.mode == "wrap" ](https://github.com/rachartier/tiny-inline-diagnostic.nvim/blob/c66cb0dcb1bd93e016cfbfdb4780ab5ccf65d42a/lua/tiny-inline-diagnostic/chunk.lua#L214). Is this intentional? could you document it if that?

**Comment by rachartier** [comment]
It is not. I will look at it tommorow. I'll let you informed, sorry for the inconvenience

**Comment by jiz4oh** [comment]
no worries, I can fix it locally first

**Comment by rachartier** [comment]
That's fixed. Thanks !
