### ISSUE TITLE
plugin does not display when the diagnosis is huge

### ISSUE THREAD

**Issue by foldcat** [rachartier/tiny-inline-diagnostic.nvim#3]
![Screenshot_20240630-224946_Termux](https://github.com/rachartier/tiny-inline-diagnostic.nvim/assets/151979723/450908a0-52ed-4344-aaa7-1b2a69601690)
as seen from the screenshot, this plugin is unable to handle hls's huge textwall error while other smaller error can be displayed

**Comment by rachartier** [comment]
Hello,

Yes I think it is because you have `vim.opt.wrap = true`. I had the same problem on markdown file. I will try to fix it !

**Comment by rachartier** [comment]
I think it is now fixed. It (normally) works. Please update and test it, and give me your feedback!
