### ISSUE TITLE
[Feature Request] Filtering Diagnostics by Severity

### ISSUE THREAD

**Issue by simoesd** [rachartier/tiny-inline-diagnostic.nvim#34]
Hi, I've been looking for a plugin like this for a while and it's great. The one feature I'm missing is the possibility of filtering diagnostics by severity, similar to `vim.diagnostic.config()`.
Currently, I use it to hide underlines and inline diagnostics for Hints and Info types while keeping those in visible in the gutter and floats, but haven't figured out a way to keep this behavior while using tiny-inline-diagnostic.
Any chance you'd add something similar to this?

**Comment by rachartier** [comment]
Hello,
Good idea, I will try to implement it soon!
I'll come back to you when it's done.

Le mer. 28 août 2024, 12:13, David Simões ***@***.***> a
écrit :

**Comment by rachartier** [comment]
Hello,
It should be good now. You can try to filter it with:
```
opts = {
     options = {
		-- Filter by severity.
		severity = {
			vim.diagnostic.severity.ERROR,
			vim.diagnostic.severity.WARN,
			vim.diagnostic.severity.INFO,
			vim.diagnostic.severity.HINT,
		},
     }
}
```

**Comment by simoesd** [comment]
Works like a charm, thank you!
