### ISSUE TITLE
Bug: inline diagnostics still showing after calling vim.diagnostic.enable(false)

### ISSUE THREAD

**Issue by strayer** [rachartier/tiny-inline-diagnostic.nvim#36]
I'm currently disabling diagnostics for gp.nvim chat windows since markdownlint is not helpful there. This is the autocmd I'm using to achieve that:

```lua
M.setup_autocommand = function()
  local disable_gp_chats_diagnostics_group = vim.api.nvim_create_augroup("DisableGpChatsDiagnostics", { clear = true })

  vim.api.nvim_create_autocmd({ "BufNewFile", "BufRead" }, {
    pattern = { "**/gp/chats/**" },
    callback = function()
      vim.diagnostic.enable(false)
    end,
    group = disable_gp_chats_diagnostics_group,
  })
end
```

This does disable diagnostics in general (no more curly lines, no more icons with the line numbers) but when the cursor is in a line with a diagnostic it still shows up.

After `vim.diagnostic.enable(false)`:

<img width="839" alt="grafik" src="https://github.com/user-attachments/assets/4326a398-b763-4edc-9e93-868ab2561c46">

After `vim.diagnostic.enable(true)`:

<img width="839" alt="grafik" src="https://github.com/user-attachments/assets/e60bf324-a703-41e6-b160-3b66db52c0a9">

**Comment by rachartier** [comment]
Should be fixed now. Thanks !

**Comment by strayer** [comment]
Works great, thank you! ❤️
