### ISSUE TITLE
Does not work with PHP :(

### ISSUE THREAD

**Issue by uwla** [rachartier/tiny-inline-diagnostic.nvim#37]
Does not work with `php`

![TINYDIAGNOSTIC](https://github.com/user-attachments/assets/f20bf883-e984-4019-a172-0262f3655ac6)

I'm using `phpactor` with `lspconfig`

**Comment by rachartier** [comment]
If you try to remove `event` from lazy, does it works each time?
It is a strange issue ! If it is random, I think maybe lazyloading with "VeryLazy" can be the cause. 

Tell me if it works without lazy loading, it will be easier to debug

**Comment by rachartier** [comment]
That's strange !
Maybe change `event` to LspAttach ?
Or you can try tweaking `priority` of the plugin from lazy.nvim.
