### ISSUE TITLE
Diagnostics not shown from nvim-lint

### ISSUE THREAD

**Issue by danielyrovas** [rachartier/tiny-inline-diagnostic.nvim#40]
I've set this plugin up alongside [nvim-lint](https://github.com/mfussenegger/nvim-lint). I have had no issue getting the (excellent) UI popping up for the errors from lua_lsp, however, I can't seem to get diagnostics from nvim-lint to appear. I believe they should work :tm: because nvim-lint is supposed to report the warnings to `vim.diagnostic`. 
I can see the diagnostics from nvim-lint in the normal neovim popup if I use `vim.diagnostic.open_float()`

I'm using no config:
```lua
{
    "rachartier/tiny-inline-diagnostic.nvim",
    event = "VeryLazy",
    opts = {},
},
```

**Comment by danielyrovas** [comment]
Yeah sure, here is a setup that shows the issue - this config doesn't have LSP setup, only nvim-lint.


<details>
<summary>ruby.rb</summary>

```ruby
def stomp("literal")
end
```

</details>

rubocop: 1.62.1
<details>
<summary>nvim --version</summary>

```
NVIM v0.11.0-nightly+0346666
Build type: Release
LuaJIT 2.1.1713773202
   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/nix/store/qi698aa2xcsg6jk2s1jw5fdz64fq3ild-neovim-unwrapped-nightly/share/nvim"
```

</details>
<details>
<summary>NVIM_APPNAME=nvd nvim -u config.lua ruby.rb</summary>

```lua
-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
    local lazyrepo = "https://github.com/folke/lazy.nvim.git"
    local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
    if vim.v.shell_error ~= 0 then
        vim.api.nvim_echo({
            { "Failed to clone lazy.nvim:\n", "ErrorMsg" },
            { out, "WarningMsg" },
            { "\nPress any key to exit..." },
        }, true, {})
        vim.fn.getchar()
        os.exit(1)
    end
end
vim.opt.rtp:prepend(lazypath)

vim.g.mapleader = " "
vim.g.maplocalleader = "\\"
vim.diagnostic.config({ virtual_text = false })

require("lazy").setup({
    spec = {
        {
            {
                "rachartier/tiny-inline-diagnostic.nvim",
                event = "VeryLazy",
                opts = {},
            },
        },
        {
            "mfussenegger/nvim-lint",
            event = "VeryLazy",
            opts = {},
            config = function(_, opts)
                local lint = require("lint")
                -- lint.linters_by_ft = {}
                vim.api.nvim_create_autocmd({ "BufWritePost", "InsertLeave" }, {
                    callback = function()
                        lint.try_lint(nil, { ignore_errors = true })
                    end,
                })
            end,
        },
    },
})
```

</details>

here is a screenshot with the diagnostics: ![image](https://github.com/user-attachments/assets/e842b10c-7a9b-4aaf-b5a6-2adc77c6adaf)

**Comment by rachartier** [comment]
I don't have the same linting messages as you, but it seems to be working (no LSP on Ruby here):
![image](https://github.com/user-attachments/assets/a8a6667a-4bbd-4309-afc5-3f462667c18d)

Maybe it comes from your linter configuration?

**Comment by danielyrovas** [comment]
Idk what nvim-lint was picking up before, but if I set nvim-lint to only use rubocop I get the same lint messages as you, but still no diagnostic from tiny-inline :(
```lua
lint.linters_by_ft = {
    ruby = { "rubocop" },
}
```

thanks for the great project btw

**Comment by rachartier** [comment]
Thanks!

Just to be sure, can you try setting opts like so:

```lua
require("tiny-inline-diagnostic").setup({
    options = {
        multilines = true,
    },
})
```

**Comment by danielyrovas** [comment]
Thanks, but same result unfortunately:
![image](https://github.com/user-attachments/assets/a3785e69-2fd8-49e7-bf46-a1580998fea9)

I also tried nvim v10 and same result.

**Comment by rachartier** [comment]
Are you lazy loading nvim-lint ? If so, just try to disable it, to check if it comes from here

**Comment by danielyrovas** [comment]
It persists if I use this config with lazy=false

<details>
<summary>config</summary>

```lua
-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
    local lazyrepo = "https://github.com/folke/lazy.nvim.git"
    local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
    if vim.v.shell_error ~= 0 then
        vim.api.nvim_echo({
            { "Failed to clone lazy.nvim:\n", "ErrorMsg" },
            { out, "WarningMsg" },
            { "\nPress any key to exit..." },
        }, true, {})
        vim.fn.getchar()
        os.exit(1)
    end
end
vim.opt.rtp:prepend(lazypath)

vim.g.mapleader = " "
vim.g.maplocalleader = "\\"
vim.diagnostic.config({ virtual_text = false })

require("lazy").setup({
    spec = {
        {
            "rachartier/tiny-inline-diagnostic.nvim",
            event = "VeryLazy",
            lazy = false,
            opts = {
                options = {
                    multilines = true,
                },
            },
        },
        {
            "mfussenegger/nvim-lint",
            event = "VeryLazy",
            lazy = false,
            opts = {},
            config = function(_, opts)
                local lint = require("lint")
                lint.linters_by_ft = {
                    ruby = { "rubocop" },
                }
                vim.api.nvim_create_autocmd({ "BufWritePost", "InsertLeave" }, {
                    callback = function()
                        lint.try_lint(nil, { ignore_errors = true })
                    end,
                })
            end,
        },
    },
})

```

</details>

**Comment by rachartier** [comment]
Thank you very much for this minimal config.

I've found the issue: inside the plugin, I create an autocmd for the LspEvent, which never triggers in your case.

So, I've added options.overwrite_events, which ideally shouldn't be modified, but in your case, it's the only solution.

What you need to do is set `options.overwrite_events = { "BufWritePre" }`, and it should work.

**Comment by 007pig** [comment]
The optimal set of `overwrite_events` appears to be `{ "DiagnosticChanged" }`.
