### ISSUE TITLE
[Feature Request] Suppress LazyVim popup

### ISSUE THREAD

**Issue by fpohtmeh** [rachartier/tiny-inline-diagnostic.nvim#41]
LazyVim is one of the most popular nvim distributions. It would be great if adding the plugin automatically disables the default LazyVim popup
![image](https://github.com/user-attachments/assets/7e685ca0-97c0-4530-920c-c53ed0e539b8)

Alternatively, it may be helpful to include a tip in the README on how to do it.

**Comment by rachartier** [comment]
I don't use LazyVim, so I'm not familiar with how it works. The popup you're referring to is probably triggered by vim.diagnostic.open_float().

I noticed it's defined here in LazyVim: [link](https://github.com/LazyVim/LazyVim/blob/13a4a84e3485a36e64055365665a45dc82b6bf71/lua/lazyvim/config/keymaps.lua#L107).

Does the popup automatically display when hovering over an error?

**Comment by fpohtmeh** [comment]
It's displayed in the following actions:
- `[d, ]d` - navigation to previous diagnostic message
- `<leader>cd` - a special mapping to trigger the popup

**Comment by rachartier** [comment]
I don't quite understand how this relates to the plugin. 
It's entirely related to your configuration.

**Comment by fpohtmeh** [comment]
Sometimes, a plugin can override the behaviour of other distros or similar plugins.
But you are right, it's not the case.

Finally, I fixed it by overwriting the `diagnostic_goto` function to this
```lua
local diagnostic_goto = function(next, severity)
  local go = next and vim.diagnostic.goto_next or vim.diagnostic.goto_prev
  severity = severity and vim.diagnostic.severity[severity] or nil
  return function()
    go({ severity = severity, float = false })
  end
end
```
and remapping the keys

Hopefully, this snippet will help other users to use your plugin instead of Neovim popup.
Thank you for the help!

**Comment by rachartier** [comment]
Well played !
Thanks for writing your solution.

Have a nice day

**Comment by philschonholzer** [comment]
> Sometimes, a plugin can override the behaviour of other distros or similar plugins. But you are right, it's not the case.
> 
> Finally, I fixed it by overwriting the `diagnostic_goto` function to this
> 
> Hopefully, this snippet will help other users to use your plugin instead of Neovim popup. Thank you for the help!

How/where did you overwrite it in the LazyVim config files?

**Comment by philschonholzer** [comment]
Ok, found out myself. 

I added this to `nvim/lua/config/keymaps.lua`

```lua
local map = vim.keymap.set

-- diagnostic
local diagnostic_goto = function(next, severity)
  local go = next and vim.diagnostic.goto_next or vim.diagnostic.goto_prev
  severity = severity and vim.diagnostic.severity[severity] or nil
  return function()
    go({ severity = severity, float = false })
  end
end
map("n", "<leader>cd", vim.diagnostic.open_float, { desc = "Line Diagnostics" })
map("n", "]d", diagnostic_goto(true), { desc = "Next Diagnostic" })
map("n", "[d", diagnostic_goto(false), { desc = "Prev Diagnostic" })
map("n", "]e", diagnostic_goto(true, "ERROR"), { desc = "Next Error" })
map("n", "[e", diagnostic_goto(false, "ERROR"), { desc = "Prev Error" })
map("n", "]w", diagnostic_goto(true, "WARN"), { desc = "Next Warning" })
map("n", "[w", diagnostic_goto(false, "WARN"), { desc = "Prev Warning" })
```

and it's working! 🎉
