### ISSUE TITLE
Setup with lazyvim

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [rachartier/tiny-inline-diagnostic.nvim#43]
Has anyone a working setup with lazyvim? I tried the following:

```
return {
  "rachartier/tiny-inline-diagnostic.nvim",
  event = "BufEnter",
  config = function()
    vim.diagnostic.config({ virtual_text = false })
    require("tiny-inline-diagnostic").setup()
  end,
}
```

But the virtual text diagnostics are still visible. I can disable them with running the disable command after entering the buffer manually, but of course I want to have that automatic.

Also it works only for me if I set hte event to "BufEnter". I would prefer something like "VeryLazy", but that does not work. Anyone knows why?

Thanks!

**Comment by RudolfVonKrugstein** [comment]
Correction: VeryLazy works, but the virtual text diagnositcs are still there ...

**Comment by rachartier** [comment]
Maybe try to set `virtual_text = false` in `diagnostics`: [https://www.lazyvim.org/plugins/lsp#nvim-lspconfig](https://www.lazyvim.org/plugins/lsp#nvim-lspconfig)

**Comment by fpohtmeh** [comment]
I adapted it for LazyVim, check this thread: https://github.com/rachartier/tiny-inline-diagnostic.nvim/issues/41

**Comment by RudolfVonKrugstein** [comment]
Works, thank you guys!
