### ISSUE TITLE
If terminal line-height is not default then border radius character isn't the right size. 

### ISSUE THREAD

**Issue by caliguIa** [rachartier/tiny-inline-diagnostic.nvim#47]
First off thank you for this plugin, it's great.
I set my terminal font line-height to be larger than normal as I am dyslexic.

<img width="718" alt="Screenshot 2024-10-14 at 18 46 00" src="https://github.com/user-attachments/assets/16578a2c-aecc-4734-ae76-fa49a414f351">

I've attached an image of what happens to the curved edges of the diagnostics virtual text when this is the case.

As you can see, because my line-height doesn't equate to my font size, the character used for the curved edges are smaller than that of the rest of the diagnostic's background. 

Now I'm assuming that because neovim is just a TUI, and only renders text, that there is no way to make the curved edges fill the full height of the line, as this would mean a character is larger than the font-size. I may be wrong about this but it's an educated guess.

What I propose as a solution would be to make the curved edges character a configurable opt. Or just have an opt for border style 'round' or 'hard'.

Let me know what you think, I'm happy to take a stab at a PR if you think this is in scope!

**Comment by rachartier** [comment]
Hello,

Ha! That's funny, on WezTerm I do not have this issue (I've greatly exaggerated the line height):
![image](https://github.com/user-attachments/assets/d72bfdb0-9eb2-44a3-a3cf-19f76c729667)

It's already configurable! You can set it here:
```lua
require("tiny-inline-diagnostic").setup({
	signs = {
		left = "",             -- the (| one
		right = "",          -- the |) one
		diag = "●",
		arrow = "    ",
		up_arrow = "    ",
		vertical = " │",
		vertical_end = " └",
	},
}
```

**Comment by caliguIa** [comment]
Oh damn, I don't know how I missed that i read through the read me twice before posting this... embarrassing! Thanks!

 I've been meaning to try out Wezterm recently anyway (currently using alacritty), so may try this out over the next couple days. 

Anyway thank you and apologies for wasting your time with this!

**Comment by rachartier** [comment]
Yes, WezTerm is really, really good.
I've tested many terminals, but I always come back to it.

The next one to test is the hyped Ghostty... when it is released!

Have a nice day !

**Comment by caliguIa** [comment]
There's a big appeal of not having to use tmux and just use wezterms built in multiplexing, one less thing to have to think about/configure! Also I miss font ligatures, which I believe wezterm supports. 

But yes, ghostty has been on my radar for a while, been patiently waiting on the discord for an invite, but think public beta release is happening by the end of the year.
