### ISSUE TITLE
[BUG] Severities in `severity` config are misinterpreted

### ISSUE THREAD

**Issue by mdietrich16** [rachartier/tiny-inline-diagnostic.nvim#49]
In [this line](https://github.com/rachartier/tiny-inline-diagnostic.nvim/blob/f5c1bc61e4f6b926cb8327c6b9839564f8e2f355/lua/tiny-inline-diagnostic/diagnostic.lua#L87), the code checks the current list of diagnostics for matches against the `config.options.severity` table. However, since the tables is a list with items representing the severities, the _indices_ the code is checking against are *not* actually the severities, but just plain indices dependent on the order of items in the `config.options.severity` table.
I think, the simplest (but definitely not best) fix would be just to check against the items themselves, e.g.:
```lua
    for _, diag in ipairs(diagnostics) do
        for _, diag_sev in ipairs(severity_filter) do
	    if diag_sev == diag.severity then
	        table.insert(diags_filtered, diag)
	    end
	end
    end
```
If I have some time this week I might be able to create a better PR for this.

**Comment by rachartier** [comment]
Thanks! I've modified it like this:

```lua

	for _, diag in ipairs(diagnostics) do
		if vim.tbl_contains(severity_filter, diag.severity) then
			table.insert(diags_filtered, diag)
		end
	end
```
But the principle is the same.

Have a nice day!
