### ISSUE TITLE
Diagnostics still showing on different buffer

### ISSUE THREAD

**Issue by elsesiy** [rachartier/tiny-inline-diagnostic.nvim#51]
Hi @rachartier,

first of all thank you for such a great plugin, I'm eager to adopt it!
I'm using NvChad and have set things up as documented, here's my config:

```
-- plugin install
{
	"rachartier/tiny-inline-diagnostic.nvim",
	event = "VeryLazy",
	config = function()
		require("tiny-inline-diagnostic").setup()
	end,
},

-- nvchad
{
	"neovim/nvim-lspconfig",
	config = function()
		require("nvchad.configs.lspconfig").defaults() # source: https://github.com/NvChad/NvChad/blob/v2.5/lua/nvchad/configs/lspconfig.lua#L55-L85
		vim.diagnostic.config({ virtual_text = false })
	end,
},
```

At first glance, things seem to work, e.g. my neovim configs using `lua-language-server` LSP

![Screen Shot 2024-10-17 at 11 27 55 PM](https://github.com/user-attachments/assets/9e4cda1d-6a0f-46ae-8b56-e955d2e84372)

However, opening a different file retains the diagnostics

![Screen Shot 2024-10-17 at 11 28 21 PM](https://github.com/user-attachments/assets/369bde93-d9ae-4bf4-8e7a-56136140697a)

Do you happen to have an idea what could be causing this?
Let me know if there's any additional debug info I can provide.

Thank you!

**Comment by rachartier** [comment]
Hello,

Thanks for the issue !
I will try to take a look at it tomorow.

**Comment by rachartier** [comment]
The latest fix should resolve your issue. If you can try it !
