### ISSUE TITLE
Diagnostics not showing on python with pyright

### ISSUE THREAD

**Issue by ritscAlex** [rachartier/tiny-inline-diagnostic.nvim#52]
tiny-inline-diagnostic won't be triggered in python with pyright as lsp-server. It works fine in .lua or .tex files but not in .py files.

```
{
  "rachartier/tiny-inline-diagnostic.nvim",
  event = "LspAttach",
  config = function()
	  require("tiny-inline-diagnostic").setup()
  end,
},
```

```
vim.diagnostic.config({
	virtual_text = false,
	signs = true,
	update_in_instert = false,
	underline = false,
	severity_sort = true,
	float = { border = "none" },
})
```

![image](https://github.com/user-attachments/assets/0fd5900b-80b8-4043-b22e-27f629247c35)

**Comment by rachartier** [comment]
Try to set `event` to "VeryLazy". If it doesn't work, try to disable lazyloading first and see if it is good

**Comment by rachartier** [comment]
Yes, it will depends on the LSP unfortunatly.  It would be better to not lazy load this plugin in fact...

So, does "VeryLazy" it resolve your issue ?

**Comment by edwarmv** [comment]
I'm also having this issue, it only happens when you have attached more than one LSP server.
My assumption is, this is because we are getting the diagnostics from from DiagnosticChanged event.

**Comment by rachartier** [comment]
Oh... yes it could be it.
I can't fix this right now, I'm really sorry. But tomorrow I will push a fix!

**Comment by rachartier** [comment]
Thank you @ritscAlex  for this detailed fix.

It should be fine now!
