### ISSUE TITLE
Maintain displayed diagnostics when `multilines` enabled

### ISSUE THREAD

**Issue by NicolasGB** [rachartier/tiny-inline-diagnostic.nvim#53]
Hi! First of all thank your for the plugin, i have discovered it recently and i am really enjoying it.

There's something that bothers me a little but but maybe it's by design or a limitation. Please let me know if this is the case.

With the `multilines` enabled, when my mouse hovers a line with an error all the other diagnostics disappear, i would love to maintain them, because sometimes the error in a line refers to another previous on the text.

Here is an example, when my mouse is on the line `second_error` the diagnostic in `forced_error` disappears and vice versa:

https://github.com/user-attachments/assets/0bd31369-26a7-4f4f-90fa-43977765024a

Here is the config i am using:

```lua
  {
    "rachartier/tiny-inline-diagnostic.nvim",
    event = "LspAttach",
    config = function()
      require("tiny-inline-diagnostic").setup {
        options = {
          -- If multiple diagnostics are under the cursor, display all of them.
          multiple_diag_under_cursor = true,
          -- Enable diagnostic message on all lines.
          multilines = true,
          -- Show all diagnostics on the cursor line.
          show_all_diags_on_cursorline = true,
          -- Avoid conflict with gitsigns
          virt_exts = {
            priority = 2048,
          },
        },
      }
    end,
  }
```

Let me know if there is any more information i can provide

**Comment by rachartier** [comment]
Hello, thank you!

Yes, it's intentional. I don't have a reliable method to print diagnostics on top of other diagnostics, so only the one on the current line will be shown, otherwise, it becomes really hard to read.

**Comment by NicolasGB** [comment]
Oh i see, thanks for your answer! I'll close the issue since it's by design :D

**Comment by rachartier** [comment]
Thank you a lot!

**Comment by rachartier** [comment]
Hi,

I've finally implemented it. You can check issue #82 !

**Comment by NicolasGB** [comment]
That's so nice! I'm giving it a try :smile:, thanks for letting me know !
