### ISSUE TITLE
Multiline indentation doesn't work very well with inlay hints enabled

### ISSUE THREAD

**Issue by chama-chomo** [rachartier/tiny-inline-diagnostic.nvim#56]
Multiline indentation doesn't work very well with inlay hints enabled (plugin: 	"lvimuser/lsp-inlayhints.nvim")
It would be nice to have this working together. I'll try to find time and look at it myself, too

<img width="1540" alt="image" src="https://github.com/user-attachments/assets/463e43b4-4d28-4070-9209-090dade19222">

**Comment by rachartier** [comment]
Hello!

You could also try to tweaks `opts.options.virt_text.priority` in the setup. You should also be able to fix your issue with that !

But thanks for suggesting `chrisgrieser/nvim-lsp-endhints`, it seems quite nice !
