### ISSUE TITLE
options show_source = true got truncated 

### ISSUE THREAD

**Issue by xu3s** [rachartier/tiny-inline-diagnostic.nvim#58]
When
```
options = {                              
  -- Show the source of the diagnostic.  
  show_source = true,                    
} 
```
Is set.
The diagnostic source name get truncated instead of getting wrapped along with the message.
![Screenshot_20241124_181337.jpg](https://github.com/user-attachments/assets/d7a5ea6b-c3b1-4afd-b887-7bc82a365fa8)

is it just me or is this a bug? if i could also suggest to put the diagnostic name below the mesage if enabled if possible.

if it is not an issue i will close and use the custom format.
Thank you.

**Comment by rachartier** [comment]
Hello,

No it's not normal! Thanks for pointing that out.
It is now fixed. If you can test it on your side and tell me if it is ok?

**Comment by xu3s** [comment]
its working now, thank you.
