### ISSUE TITLE
Virt Text position on smaller window

### ISSUE THREAD

**Issue by rodhash** [rachartier/tiny-inline-diagnostic.nvim#59]
When using the terminal in its normal size things work fine but when I snap my terminal to the side the Virt text gets weird to read and it moves below lines down quite a bit:

Looking normal:
<img width="1390" alt="image" src="https://github.com/user-attachments/assets/f8f7cc0e-4b54-4dc4-a1ff-c46484b8551f">

After snapping my terminal window to the side:
<img width="895" alt="image" src="https://github.com/user-attachments/assets/fbd52fdb-b50e-4a78-9a72-8c73dca416f0">

What do you think?

It doesn't feel like a bug but maybe moving the Virt text down would make more room for it and perhaps would be nicer to read the Virt text. I think this is the default behavior for long lines.

**Comment by rachartier** [comment]
You can try increasing `softwrap`:

```lua 
require("tiny-inline-diagnostic").setup({
    options = {
        softwrap = 60,
    },
})
```

**Comment by rodhash** [comment]
Yeah you're right it was the `softwrap`, it was manually set to 15 as in the README but after commenting out this line this is now fixed.

**Comment by rodhash** [comment]
Thank you.. looking way better now!

**Comment by rodhash** [comment]
Setting it to 30 also works fine, as it is in [init.lua](https://github.com/rachartier/tiny-inline-diagnostic.nvim/blob/7ec90c63692d78032d4a3355dd25811f9b587663/lua/tiny-inline-diagnostic/init.lua#L31).

Should the README be updated to suggest 30 as the default?
