### ISSUE TITLE
Question: is there any way to toggle diagnostics?

### ISSUE THREAD

**Issue by ryoppippi** [rachartier/tiny-inline-diagnostic.nvim#6]

**Comment by rachartier** [comment]
Not yet, I will try to implement it, thanks

**Comment by rachartier** [comment]
Hello again, 

I've implemented `enable`, `disable`, `toggle`. Feel free to try it out ! I've added the methods inside the README (API).

**Comment by ryoppippi** [comment]
Thank you!
I'll check it out!!!

**Comment by rachartier** [comment]
Do not hesitate to tell me if something is wrong !

**Comment by ryoppippi** [comment]
I was busy for a while so I couldn't try it.
I'll give a try
Cheers!!

**Comment by ryoppippi** [comment]
Works! Thank you for creating this amazing plugin!

**Comment by rachartier** [comment]
Thank you very much !
