### ISSUE TITLE
Adding this into neovim?

### ISSUE THREAD

**Issue by benomahony** [rachartier/tiny-inline-diagnostic.nvim#60]
This plugin is awesomeness! Have you considered contributing it back into neovim core?

**Comment by rachartier** [comment]
Thank you very much !
In core, it's a "relatively" simple feature, but it works absolutely everywhere. In my implementation, it still requires quite a bit of computation, and I don't think it's very optimized. Actually, my first personal implementation of this project was done using only vim.diagnostic, just to make it look nicer, but it didn’t include this "wrap" system or similar features. I think adding that would increase complexity quite a bit for relatively little gain (in core). Many people directly use popups or other means to display diagnostics without relying on inline diagnostics!
