### ISSUE TITLE
Border (pop up) as alternative?

### ISSUE THREAD

**Issue by rodhash** [rachartier/tiny-inline-diagnostic.nvim#61]
Hi

What if we could choose between having the HL colors as default or using borders (pop up) as an alternative?

ie: lspsaga or CMP using border:

<img width="731" alt="image" src="https://github.com/user-attachments/assets/43c12c84-43ad-49b3-977d-26dc9c0f9104">

**Comment by rachartier** [comment]
Hello,

No, it is not possible, as diagnostics renders as extmarks, and not as popups. 

Moreover, you have already `vim.lsp.buf.hover` that can do the job!
