### ISSUE TITLE
Default diagnostics still shown after `vim.diagnostic.config({ virtual_text = false })`, also tiny-inline-diagnostics only shown if cursor hovers over the line

### ISSUE THREAD

**Issue by karimcheck24** [rachartier/tiny-inline-diagnostic.nvim#62]
Hi,
My default diagnostics are still shown even after setting `vim.diagnostic.config({ virtual_text = false })`, 
also tiny-inline-diagnostics are only shown if the cursor hovers over the problematic line.

I am using LazyVim, this is my config:

```
return {
  "rachartier/tiny-inline-diagnostic.nvim",
  event = "VeryLazy",
  config = function()
    vim.diagnostic.config({ virtual_text = false })
    -- Default configuration
    require("tiny-inline-diagnostic").setup({
      signs = {
        left = "",
        right = "",
        diag = "●",
        arrow = "    ",
        up_arrow = "    ",
        vertical = " │",
        vertical_end = " └",
      },
      hi = {
        error = "DiagnosticError",
        warn = "DiagnosticWarn",
        info = "DiagnosticInfo",
        hint = "DiagnosticHint",
        arrow = "NonText",
        background = "CursorLine", -- Can be a highlight or a hexadecimal color (#RRGGBB)
        mixing_color = "None", -- Can be None or a hexadecimal color (#RRGGBB). Used to blend the background color with the diagnostic background color with another color.
      },
      blend = {
        factor = 0.27,
      },
      options = {
        -- Throttle the update of the diagnostic when moving cursor, in milliseconds.
        -- You can increase it if you have performance issues.
        -- Or set it to 0 to have better visuals.
        throttle = 20,

        -- The minimum length of the message, otherwise it will be on a new line.
        softwrap = 15,

        -- If multiple diagnostics are under the cursor, display all of them.
        multiple_diag_under_cursor = false,

        overflow = {
          -- Manage the overflow of the message.
          --    - wrap: when the message is too long, it is then displayed on multiple lines.
          --    - none: the message will not be truncated, and will be displayed on a single line.
          mode = "wrap",
        },

        --- Enable it if you want to always have message with `after` characters length.
        break_line = {
          enabled = false,
          after = 30,
        },

        virt_texts = {
          priority = 2048,
        },
      },
    })
  end,
}
```

I already tried to move the vim.diagnostic.config({ virtual_text = false }) line to the end of the config function but the problem persists.

This is what it looks like for me (while hovering over the line): 
![grafik](https://github.com/user-attachments/assets/13370c97-f116-47fa-aa70-48d7b94286c9)

If I don't hover over the line, only the default diagnostics are shown (I can tell because they don't wrap)

**Comment by rachartier** [comment]
Are you using a distro?


You need to set 
```lua
require("tiny-inline-diagnostic").setup({
    options = {
        multilines = true
    }
})
```
to enable multilines diagnostics

**Comment by Enoz** [comment]
Once you've opened a buffer and are seeing the virtual text, can you try running

`:lua vim.diagnostic.config({ virtual_text = false })`

as a command? If it resolves the issue, then there is another plugin probably overriding this value. Maybe move this line to the beginning of your `neovim/nvim-lspconfig` config if you have one.

**Comment by rachartier** [comment]
Nice! Good job.

If I can suggest, do not copy the 'opts' from the README into your config. You just need to put the attributes that you change (if there are any). In your case, a simple "{}" should be good !

**Comment by nxtkofi** [comment]
to anyone that stumbles upon this issue in the future this is the solution:
> vim.diagnostic.config({ virtual_text = false })
>     end,

You need to insert `vim.diagnostic.config({ virtual_text = false })` specifically before the function `end`. Otherwise this won't work.
I feel like this should be mentioned in documentation, no? I am not using Lazy and this was the solution for me.

**Comment by rachartier** [comment]
I will modify the readme, but I don't see why it matters.

Setting `vim.diagnostic.config({ virtual_text = false })` in fact has nothing to do with the plugin. I do not use this config table at all; it's only to tell Neovim to not display their diagnostics.

It can come from either that or `nvim-lspconfig`. I think by default it is not even enabled, as I don't need to set `virtual_text = false` in my dots.

It can maybe me some race conditions or something similar when lazy loading plugins (not only with `lazy.nvim`, but with `pckr` or `mini`)

**Comment by nxtkofi** [comment]
> I will modify the readme, but I don't see why it matters.

> It can maybe me some race conditions or something similar when lazy loading plugins (not only with `lazy.nvim`, but with `pckr` or `mini`)

That's valid, I didn't think of it from such perspective, sorry if I came off as ignorant or anything like that!
I just thought that a small note mentioning this as a solution might be helpful for future users, thanks for considering my suggestion!

**Comment by imroc** [comment]
> [@rachartier](https://github.com/rachartier) [@Enoz](https://github.com/Enoz) Thank you guys, I figured it out thanks to you guys! I had to enable multiline and overwrite the LazyVim default nvim-lspconfig diagnostic opts. For anyone using LazyVim, this is my config now:
> 
> ```
> return {
>   {
>     "rachartier/tiny-inline-diagnostic.nvim",
>     event = "VeryLazy",
>     priority = 1000,
>     config = function()
>       vim.diagnostic.config({ virtual_text = false })
>       -- Default configuration
>       require("tiny-inline-diagnostic").setup({
>         signs = {
>           left = "",
>           right = "",
>           diag = "●",
>           arrow = "    ",
>           up_arrow = "    ",
>           vertical = " │",
>           vertical_end = " └",
>         },
>         hi = {
>           error = "DiagnosticError",
>           warn = "DiagnosticWarn",
>           info = "DiagnosticInfo",
>           hint = "DiagnosticHint",
>           arrow = "NonText",
>           background = "CursorLine", -- Can be a highlight or a hexadecimal color (#RRGGBB)
>           mixing_color = "None", -- Can be None or a hexadecimal color (#RRGGBB). Used to blend the background color with the diagnostic background color with another color.
>         },
>         blend = {
>           factor = 0.27,
>         },
>         options = {
>           -- Throttle the update of the diagnostic when moving cursor, in milliseconds.
>           -- You can increase it if you have performance issues.
>           -- Or set it to 0 to have better visuals.
>           throttle = 20,
> 
>           -- The minimum length of the message, otherwise it will be on a new line.
>           softwrap = 15,
> 
>           -- If multiple diagnostics are under the cursor, display all of them.
>           multiple_diag_under_cursor = true,
> 
>           overflow = {
>             -- Manage the overflow of the message.
>             --    - wrap: when the message is too long, it is then displayed on multiple lines.
>             --    - none: the message will not be truncated, and will be displayed on a single line.
>             mode = "wrap",
>           },
> 
>           --- Enable it if you want to always have message with `after` characters length.
>           break_line = {
>             enabled = false,
>             after = 30,
>           },
> 
>           virt_texts = {
>             priority = 2048,
>           },
> 
>           multilines = true,
>         },
>       })
>       vim.diagnostic.config({ virtual_text = false })
>     end,
>   },
>   {
>     "neovim/nvim-lspconfig",
>     opts = { diagnostics = { virtual_text = false } },
>   },
> }
> ```

I've tried this in both `v0.11.1` and `v0.11.2` with LazyVim, it didn't work.

virtual text is still there:

<img width="1582" alt="Image" src="https://github.com/user-attachments/assets/b36cec82-4447-45e0-9460-36d2a9e421e4" />

If remove this plugin, it's even less virtual text:

<img width="1372" alt="Image" src="https://github.com/user-attachments/assets/73b04317-5ad0-47d0-bc5e-6855526e37a8" />

**Comment by rachartier** [comment]
Did you try to set `virtual_text = false` here? https://www.lazyvim.org/plugins/lsp#nvim-lspconfig

**Comment by imroc** [comment]
> Did you try to set `virtual_text = false` here? https://www.lazyvim.org/plugins/lsp#nvim-lspconfig

I just solved this problem, but not for this reason, cuz the config below already set virtual_text to false:
```lua
  {
    "neovim/nvim-lspconfig",
    opts = { diagnostics = { virtual_text = false } },
  },
```

After my debugging, I found that it was because I installed [go.nvim](https://github.com/ray-x/go.nvim), it'll run `vim.diagnostic.config` by default: 

<img width="611" alt="Image" src="https://github.com/user-attachments/assets/d8212845-59a0-4741-a6f4-3643a1dcf6b1" />

And it can be disabled by set to false:

<img width="727" alt="Image" src="https://github.com/user-attachments/assets/515ed7a0-946f-485a-9d35-c90b4510a62f" />

Here is my config:
https://github.com/imroc/dotfiles/blob/2dfe7d83d256c04d2375bad71a16dda563537f94/.config/nvim/lua/plugins/lang/go.lua#L11-L11

https://github.com/imroc/dotfiles/blob/2dfe7d83d256c04d2375bad71a16dda563537f94/.config/nvim/lua/plugins/coding/tiny-inline-diagnostic.lua
