### ISSUE TITLE
Inline diagnostics add empty lines but only sometimes

### ISSUE THREAD

**Issue by iamim** [rachartier/tiny-inline-diagnostic.nvim#66]
Hi,

First, thank you so much for this plugin, really enjoying it!

I observed an issue when sometimes the plugin inserts empty lines but does not in other cases. I can't figure out how to configure this behavior to always render as an overlay without adding empty lines.

It seems to be similar to #14 but I do observe it on the latest version.

Here are the screenshots (I would like to achieve the second case):
<img width="1311" alt="image" src="https://github.com/user-attachments/assets/9b075493-be0a-4e97-8fb7-994026c61cc5">
<img width="1311" alt="image" src="https://github.com/user-attachments/assets/b85b9079-ff0c-42db-85b8-20f38218258a">

**Comment by rachartier** [comment]
Hi again,

It should be fixed now

**Comment by iamim** [comment]
It worked, thank you!

I now noticed another thing: when rendering diagnostics it renders over some text with the same color as the background making it look like the text has disappeared.

Do you think it is possible to make the portion under the `<-` transparent? Would you like me to create an issue?
<img width="1276" alt="image" src="https://github.com/user-attachments/assets/30a025c9-1a2b-473e-b0df-ce1175f8dce9">
<img width="1068" alt="image" src="https://github.com/user-attachments/assets/33bd4061-809e-4427-bd70-94d94c4aa57d">

**Comment by rachartier** [comment]
Yes it is possible, but in fact it doesn't look good in long term. It is much harder to read if there is no space between the text and the diagnostic

**Comment by iamim** [comment]
Perhaps it could be solved by making it configurable and allowing people to specify it's `winblend` value?

**Comment by rachartier** [comment]
It is now a window, IFAIK winblend only works for those ! The plugin uses virtual lines/texts

I can try to look for a solution
