### ISSUE TITLE
Ability to use configured vim diagnostic signs

### ISSUE THREAD

**Issue by acoffman** [rachartier/tiny-inline-diagnostic.nvim#67]
Hi, awesome plugin!

Right now, the "icon" that is displayed is the same for all types of diagnostics and is configured via the `signs.diag` option in the plugin setup.

Neovim however already lets you [configure](https://neovim.io/doc/user/diagnostic.html#diagnostic-signs) specific signs for your diagnostics via `vim.diagnostic.config.signs`. Other plugins like folke's trouble will use those signs automatically for the various diagnostic types. I was wondering if it would be possible to either provide this behavior as an option, or allow it to be configured rather than just having one sign for all types of diagnostics.

(I am also happy to attempt a PR for this behavior if desired)

**Comment by rachartier** [comment]
Hi, thank you !

I did add it. You need to set:
```lua
{
     options = {
          use_icons_from_diagnostic = true
     }
}
```
And it will fetch signs from your `vim.diagnostic` config.

Also, I did a major overhaul of the code, so it may be unstable. Do not hesitate to tell me if something is wrong

**Comment by acoffman** [comment]
Amazing, thanks!
