### ISSUE TITLE
Default wrapping hides contents when there's not enough space left

### ISSUE THREAD

**Issue by yamafaktory** [rachartier/tiny-inline-diagnostic.nvim#69]
Hi and thanks a ton for this awesome plugin! I like how clean diagnostics are being displayed :)

Just noticed that if the space left for the diagnostics is too small, we are missing the full message (using default config with "ghost"):

![image](https://github.com/user-attachments/assets/2a119a29-cfee-466a-b766-30c50518e7c1)

**Comment by rachartier** [comment]
Hi, thank you very much!

I think it's because of the other virtual texts inside the line. Can you tell me which plugin it is, please?

**Comment by yamafaktory** [comment]
Hi @rachartier,

Thanks for the swift feedback! Your assumption about virtual texts is indeed correct. The issue is that this is not caused by a plugin but a consequence of the built-in nvim LSP functionality for inlay hints.

Here is the faulty line:

```lua
  if client.server_capabilities.inlayHintProvider then
    vim.lsp.inlay_hint.enable(true)
  end
```

## Without inlay hints (works perfectly)
![image](https://github.com/user-attachments/assets/8c47e450-53c6-44fc-902d-ffeaea7ca57a)

## With inlay hints (broken)
![image](https://github.com/user-attachments/assets/56d23d16-737a-4b24-9542-2acf1785900f)

**Comment by yamafaktory** [comment]
Forgot to mention that I'm correctly disabling the virtual text:

```lua
vim.diagnostic.config({
  update_in_insert = true,
  virtual_text = false,
})
```

**Comment by rachartier** [comment]
Seems fixed !
Can you update and tell me if it is good on your end?

![image](https://github.com/user-attachments/assets/512b0e4a-1250-4e4f-9f4f-41ac638594de)

**Comment by yamafaktory** [comment]
`tsserver` -> https://github.com/yamafaktory/.config/blob/7a2cda57bcf84c23fb72ef795fc6ce88e45d34e0/nvim/init.lua#L669

**Comment by yamafaktory** [comment]
But I don't think that the LSP itself is relevant here. E.g. this is a Zig file where I'm adding an additional semi-colon at the end of a line:

![image](https://github.com/user-attachments/assets/b7f89e1d-047f-48bb-8c28-19f94640b9d4)

**Comment by rachartier** [comment]
I think I found the issue. Can you please update and retry?

**Comment by yamafaktory** [comment]
Awesome :)

Thanks a ton @rachartier - works like a charm now!

![image](https://github.com/user-attachments/assets/0cf3461d-cd75-451c-bd4f-a533c1e96cd7)

Thanks for a former inhabitant of Volvic (long long time ago) ;)

**Comment by rachartier** [comment]
Wow! That's the first time I've heard someone online mention Volvic! That's so cool!

I hope you have a wonderful day :)
