### ISSUE TITLE
`use_icons_from_diagnostic = true` doesn´ t work with Neovim 0.10+

### ISSUE THREAD

**Issue by noirbizarre** [rachartier/tiny-inline-diagnostic.nvim#70]
Settings `use_icons_from_diagnostic = true` with Neovim 0.10+ fails with:

```
   Error  22:28:39 msg_show.lua_error Erreur détectée en traitant Autocommandes DiagnosticChanged pour "*"..Autocommandes User pour "TinyDiagnosticEvent" :
22:28:39 msg_show Error executing lua callback: ...iagnostic.nvim/lua/tiny-inline-diagnostic/highlights.lua:236: attempt to index field 'signs' (a boolean value)
stack traceback:
	...iagnostic.nvim/lua/tiny-inline-diagnostic/highlights.lua:236: in function 'get_diagnostic_icon'
	...ine-diagnostic.nvim/lua/tiny-inline-diagnostic/chunk.lua:85: in function 'get_header_from_chunk'
	...gnostic.nvim/lua/tiny-inline-diagnostic/virtual_text.lua:38: in function 'build_first_chunk'
	...gnostic.nvim/lua/tiny-inline-diagnostic/virtual_text.lua:85: in function 'from_diagnostic'
	...gnostic.nvim/lua/tiny-inline-diagnostic/virtual_text.lua:144: in function 'from_diagnostics'
	...iagnostic.nvim/lua/tiny-inline-diagnostic/diagnostic.lua:138: in function 'apply_virtual_texts'
	...iagnostic.nvim/lua/tiny-inline-diagnostic/diagnostic.lua:237: in function <...iagnostic.nvim/lua/tiny-inline-diagnostic/diagnostic.lua:233>
	[C]: in function 'nvim_exec_autocmds'
	...iagnostic.nvim/lua/tiny-inline-diagnostic/diagnostic.lua:224: in function <...iagnostic.nvim/lua/tiny-inline-diagnostic/diagnostic.lua:222>
	[C]: in function 'nvim_exec_autocmds'
	/usr/share/nvim/runtime/lua/vim/diagnostic.lua:1033: in function 'set'
	/usr/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:257: in function 'handle_diagnostics'
	/usr/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:327: in function 'handler'
	/usr/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

(There's some french in there, sorry)

The faulty line is https://github.com/rachartier/tiny-inline-diagnostic.nvim/blob/main/lua/tiny-inline-diagnostic/highlights.lua#L236 as `vim.diagnostics.config().signs` is a boolean.

For reference, [here's how it's done in trouble](https://github.com/folke/trouble.nvim/blob/main/lua/trouble/format.lua#L88-L114) and made few trials, fetching icon with `vim.fn.sign_getdefined` is working, but I only have Neovim 0.10.2, and I can't guarantee that if I submit a fix it will be backward compatible.

**Comment by rachartier** [comment]
Hello, pas de souci je suis français aussi :)

It really depends on how you configure your sign. If you defined it like I did in my config: https://github.com/rachartier/dotfiles/blob/16f8512a20525671a4b11877671d69e0c8e595c0/.config/nvim/lua/config/diagnostic.lua#L43C1-L50C4
It will not output any errors! So I can't really test what does not work on your side.

Nevertheless, I did try to fix it. Can you please update it and tell me if it is good? If not, can you send me how you define your signs so that I can test better?
