### ISSUE TITLE
Feature: Display icons but not full messags on all lines

### ISSUE THREAD

**Issue by baroldgene** [rachartier/tiny-inline-diagnostic.nvim#72]
This plugin is amazing and looks great!  One thing I'm missing is the ability to show the icon (dot, amongus, whatever) on all lines with issues but only show the message when the cursor is on that line.

**Comment by rachartier** [comment]
Hi, thanks !

I've added `options.add_messages`:
![image](https://github.com/user-attachments/assets/33c53d44-e8ae-4629-a71c-b351b447acc7)

![image](https://github.com/user-attachments/assets/095d99a3-f813-4398-8f8e-cb3a7d79a12c)

Try to update, and tell me if it does what you want !

**Comment by baroldgene** [comment]
Oh I also have this in my `options.lua`

`vim.diagnostic.config({ virtual_text = false, signs = true, underline = true })`

**Comment by baroldgene** [comment]
🤦 

That was totally it.  Updated and it works great.  Thank you!

**Comment by rachartier** [comment]
Have a nice day !
