### ISSUE TITLE
Permanently disable

### ISSUE THREAD

**Issue by ADIX7** [rachartier/tiny-inline-diagnostic.nvim#74]
Currently there are API methods for enable/disable/toggle, but it "auto enables" at least on ModeChanged, si it is a little bit confusing (or at least it was for me). It would be great if there would be an option to permanently disable diagnostics.  
Also, it would be nice if there would be an option to disable by default, although it might be something more specific for my use case.

I use this plugin in conjunction with [lsp_lines](https://git.sr.ht/~whynothugo/lsp_lines.nvim). I have a keymap that toggles both, so when I need the verbosity (and that fancy line to a specific part of the code) I use lsp_lines but when it is too much noise (and takes up too much space) I toggle both and use this awesome plugin to nicely show the diag message.

**Comment by rachartier** [comment]
That was a bug, thanks for pointing it out.

Can you try updating and tell me if it is good on your side? The API should now do what it is supposed to do!

**Comment by ADIX7** [comment]
Yes, it is working now, thank you for the quick fix! I thought it is a feature :smile:
