### ISSUE TITLE
Presets not working

### ISSUE THREAD

**Issue by adriafarres** [rachartier/tiny-inline-diagnostic.nvim#75]
Hello there,

Thank  you for this plugin. I've been quite happy with it :-)

There's been some refactoring a couple of days ago that I believe has broken the preset functionality, as I can't seem to change the appearence while defining it with 

```
opts = {
  preset = 'simple',
},
```

which worked a few days ago.

**Comment by rachartier** [comment]
Thanks !

Should be fixed, sorry. Can you try please?

**Comment by adriafarres** [comment]
It is indeed fixed :-) Thank you!
