### ISSUE TITLE
Inline diagnostics remain being displayed after changing select mode to insert mode

### ISSUE THREAD

**Issue by nowaylifer** [rachartier/tiny-inline-diagnostic.nvim#77]
E.g. during snippet expansions:

https://github.com/user-attachments/assets/705fb4c9-0c90-4c67-833c-bb71faf63d63

Compared with plain virtual text:

https://github.com/user-attachments/assets/0dd95d5d-37d2-4317-a0c8-077b73840c6c

**Comment by rachartier** [comment]
Hi,

Should be fixed. Can you update and try?

**Comment by nowaylifer** [comment]
> Hi,
> 
> Should be fixed. Can you update and try?

works good, thanks
