### ISSUE TITLE
Question: is spellwarn.nvim supported

### ISSUE THREAD

**Issue by grimnight** [rachartier/tiny-inline-diagnostic.nvim#79]
I recently found [spellwarn.nvim] and tried to get it to work with _tiny-inline-diagnostic.nvim_, but I was unable to get it to work.

[spellwarn.nvim]: https://github.com/ravibrock/spellwarn.nvim
[tiny-inline-diagnostic.nvim]: https://github.com/rachartier/tiny-inline-diagnostic.nvim

**Comment by rachartier** [comment]
Did you already have an LSP started in your buffer, or was it only spellwarn?

**Comment by rachartier** [comment]
Works great on my side:
![image](https://github.com/user-attachments/assets/8740eda4-59d2-4b1b-8843-602fba312cdd)

Did you follow the installation procedure from spellwarn by setting `vim.opt.spell = true` and `vim.opt.spelllang = { "en" }`?

**Comment by rachartier** [comment]
I'm not here to debug your configuration, sorry as your minimal configuration doesn't even work.

For making the plugin to work in your case, you needs to either have an LSP or have `options.overwrite_events = {"DiagnosticChanged"}` set.

In your minimal example, you don't have Mason or LSPConfig set up, so you'll need to configure `overwrite_events` for it to work.
