### ISSUE TITLE
Overlap with other plugins' output

### ISSUE THREAD

**Issue by mortymacs** [rachartier/tiny-inline-diagnostic.nvim#80]
Hi,

I'm using other plugins to display the usage count and implementation of a function. When there's an issue with that line, the error appears under those elements. I tried changing the priority of the virt_texts in the config, but it didn't help.

![image](https://github.com/user-attachments/assets/6f1f367b-ec99-4ce9-b796-0c233c87c181)

```lua
require("tiny-inline-diagnostic").setup()
```
NVIM v0.10.2

Any idea how to fix it?
Thanks!

**Comment by rachartier** [comment]
Hi,

You can try to tweaks 
```lua
{
     options = {
          virt_texts = {
                 priority = 2048,
          }
     }
},
```

To adjust which one has priority over others

**Comment by mortymacs** [comment]
The issue was with the other plugin. Although I had already changed `virt_texts` in your plugin, I still received the same output. I just realized that the other plugin had higher priority number, and by changing its `vt_priority` to a lower number, the issue was resolved.
Thanks!
