### ISSUE TITLE
[Bug]: Cursorline and multiline options block each other out

### ISSUE THREAD

**Issue by Torathion** [rachartier/tiny-inline-diagnostic.nvim#82]
With this configuration,

```lua
    require('tiny-inline-diagnostic').setup({
        preset = 'modern',
        options = {
            throttle = 100,
            enable_on_insert = true,
            multiple_diag_under_cursor = true,
            show_all_diags_on_cursorline = true,
            multilines = true
        }
    })
```

When I  go close or inside the context of any diagnostic warning, only the cursorline diagnostic warning is shown and all surrounding diagnostic warnings  go away.

Outside context (cursor is on a random string)

![screenshot_outside](https://github.com/user-attachments/assets/a800a34d-86ff-4d01-a56f-ac876c547029)

And inside context (preferably on a specific problematic line):

![screenshot_inside](https://github.com/user-attachments/assets/12509ca4-85ab-4e68-b19f-b04567951abb)

Could you change the behavior so I can see everything wherever my cursor is?

(Cool plugin, btw)

**Comment by rachartier** [comment]
Hi,

Yes this is on purpose. 
I've tested without it, and it does not look good at all, as it's a lot harder to read

I can try to readd it in this version

**Comment by Torathion** [comment]
I'd be happy with an extra option. It's important for me, because when I scroll through my window to find those issues, my cursor moves as well and and that can easily lead to this issue.

**Comment by rachartier** [comment]
I'll try to add it in the next days

**Comment by rachartier** [comment]
Hi again,

I've added it. You can enable this features by doing so:
```
multilines = {                                     
	-- Enable the multilines feature               
	enable = true,                                
                                                   
	-- Always show diagnostic messages on all lines
	always_show = true,                           
}                                                  
```

Tell me if that's what you wanted !

**Comment by Torathion** [comment]
Exactly what I wanted. Great job!

**Comment by rachartier** [comment]
Thanks, it is fixed !
