### ISSUE TITLE
Diagnostic issues disappear when switching from normal to insert mode

### ISSUE THREAD

**Issue by Torathion** [rachartier/tiny-inline-diagnostic.nvim#83]
With this config:

```lua
	require('tiny-inline-diagnostic').setup({
		preset = 'modern',
		options = {
			throttle = 100,
			enable_on_insert = true,
			multiple_diag_under_cursor = true,
			show_all_diags_on_cursorline = true,
			multilines = {
				enabled = true,
				always_show = true,
			},
		},
	})
```

When I switch from normal mode to insert mode, all diagnostic lines disappear.

Normal mode:

![screenshot_diag_nomral](https://github.com/user-attachments/assets/3ca744d9-dd13-4181-8e8e-8b451f623138)

Insert mode (same cursor position):

![screenshot_diag_insert](https://github.com/user-attachments/assets/0c52bc10-bd8b-47df-9b7c-518a33933429)

I don't know if there is something interfering with this plugin or so, because I don't have any autocmds for `InsertEnter`.

**Comment by rachartier** [comment]
Yeah that's normal, you need to set `options.enable_on_insert = true` in the plugin configuration

**Comment by rachartier** [comment]
Oops sorry.

It works on my side:
![issue_inline_2](https://github.com/user-attachments/assets/f6cd61db-f662-4b33-a802-da5e8ecae173)

Event `CursorMovedI` can maybe cause a conflict on your side. Look if you have an autocmd setup for this event

**Comment by Torathion** [comment]
`:autocmd CursorMovedI *` showed me this:

```
vim_illuminate_v2_augroup  CursorMovedI
*<Lua 117: ~/.local/share/nvim/lazy/vim-illuminate/lua/illuminate/engine.lua:49>
Neominimap  CursorMovedI
*<Lua 325: ~/.local/share/nvim/lazy/neominimap.nvim/lua/neominimap/window/float/init.lua:53>
matchparen  CursorMovedI
*call s:Highlight_Matching_Pair()
SmearCursor  CursorMovedI
*lua require("smear_cursor.color").update_color_at_cursor()
lua require("smear_cursor.events").jump_cursor()
IndentBlankline  CursorMovedI
*<Lua 352: ~/.local/share/nvim/lazy/indent-blankline.nvim/lua/ibl/autocmds.lua:26>
CursorMovedI
*<Lua 769: ~/.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/lib/buffer_events.lua:67>
<Lua 780: ~/.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/lib/buffer_events.lua:67>
<Lua 784: ~/.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/completion/windows/menu.lua:46>
<Lua 787: ~/.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/signature/window.lua:33>
gitblame  CursorMovedI
*<Lua 931: ~/.local/share/nvim/lazy/git-blame.nvim/lua/gitblame/init.lua:70>
```

While `autocmd CursorMovedI` showed me this:

```
vim_illuminate_v2_augroup  CursorMovedI
*<Lua 117: ~/.local/share/nvim/lazy/vim-illuminate/lua/illuminate/engine.lua:49>
Neominimap  CursorMovedI
*<Lua 325: ~/.local/share/nvim/lazy/neominimap.nvim/lua/neominimap/window/float/init.lua:53>
matchparen  CursorMovedI
*call s:Highlight_Matching_Pair()
SmearCursor  CursorMovedI
*lua require("smear_cursor.color").update_color_at_cursor()
lua require("smear_cursor.events").jump_cursor()
IndentBlankline  CursorMovedI
*<Lua 352: ~/.local/share/nvim/lazy/indent-blankline.nvim/lua/ibl/autocmds.lua:26>
CursorMovedI
*<Lua 769: ~/.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/lib/buffer_events.lua:67>
<Lua 780: ~/.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/lib/buffer_events.lua:67>
<Lua 784: ~/.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/completion/windows/menu.lua:46>
<Lua 787: ~/.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/signature/window.lua:33>
TinyInlineDiagnosticAutocmds  CursorMovedI
<buffer=1><Lua 804: ~/.local/share/nvim/lazy/tiny-inline-diagnostic.nvim/lua/tiny-inline-diagnostic/diagnostic.lua:192> [Update diagnostics on cursor move (throttled)]
gitblame  CursorMovedI
*<Lua 931: ~/.local/share/nvim/lazy/git-blame.nvim/lua/gitblame/init.lua:70>
TinyInlineDiagnosticAutocmds  CursorMovedI
<buffer=1><Lua 830: ~/.local/share/nvim/lazy/tiny-inline-diagnostic.nvim/lua/tiny-inline-diagnostic/diagnostic.lua:192> [Update diagnostics on cursor move (throttled)]
```

I don't have any custom autocmds set up in my configuration.

Are you aware of any incompatibilities?

**Comment by rachartier** [comment]
Not that I know of.

I also use `blink.nvim`, `smear_cursor`, and was using `vim-illuminate` at some point, and all was good.

How do you load the plugin?

**Comment by Torathion** [comment]
It's the last plugin I enable.

I also tried `ModeChanged` (because I don't move my cursor between those pictures) and it's only this plugin and illuminate:

```
vim_illuminate_v2_augroup  ModeChanged
*<Lua 119: ~/.local/share/nvim/lazy/vim-illuminate/lua/illuminate/engine.lua:49>
ModeChanged
*<Lua 771: ~/.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/lib/buffer_events.lua:94>
<Lua 782: ~/.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/lib/buffer_events.lua:94>
TinyInlineDiagnosticAutocmds  ModeChanged
*<Lua 801: ~/.local/share/nvim/lazy/tiny-inline-diagnostic.nvim/lua/tiny-inline-diagnostic/diagnostic.lua:206>
<Lua 618: ~/.local/share/nvim/lazy/tiny-inline-diagnostic.nvim/lua/tiny-inline-diagnostic/diagnostic.lua:206>
ModeChanged
<buffer=1><Lua 599: ~/.local/share/nvim/lazy/noice.nvim/lua/noice/lsp/signature.lua:122>
TinyInlineDiagnosticAutocmds  ModeChanged
*<Lua 842: ~/.local/share/nvim/lazy/tiny-inline-diagnostic.nvim/lua/tiny-inline-diagnostic/diagnostic.lua:206>
ModeChanged
<buffer=83><Lua 1618: ~/.local/share/nvim/lazy/noice.nvim/lua/noice/lsp/signature.lua:122>
TinyInlineDiagnosticAutocmds  ModeChanged
*<Lua 1189: ~/.local/share/nvim/lazy/tiny-inline-diagnostic.nvim/lua/tiny-inline-diagnostic/diagnostic.lua:206>
```

What surprises me is that there is no autocmd for `InsertEnter`:

```
ALEEvents  InsertEnter
*call ale#events#InsertEnterEvent(str2nr(expand('<abuf>')))
InsertEnter
*<Lua 461: ~/.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/keymap/init.lua:54>
<Lua 770: ~/.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/lib/buffer_events.lua:67>
<Lua 781: ~/.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/lib/buffer_events.lua:67>
Signature  InsertEnter
<buffer=1><Lua 805: ~/.local/share/nvim/lazy/lsp_signature.nvim/lua/lsp_signature/init.lua:938> [signature on insert enter]
gitblame  InsertEnter
*<Lua 930: ~/.local/share/nvim/lazy/git-blame.nvim/lua/gitblame/init.lua:57>
InsertEnter
<buffer=1><Lua 613: ~/.local/share/nvim/lazy/noice.nvim/lua/noice/util/init.lua:106>
Signature  InsertEnter
<buffer=1><Lua 775: ~/.local/share/nvim/lazy/lsp_signature.nvim/lua/lsp_signature/init.lua:938> [signature on insert enter]
InsertEnter
<buffer=83><Lua 1699: ~/.local/share/nvim/lazy/noice.nvim/lua/noice/util/init.lua:106>
Signature  InsertEnter
<buffer=83><Lua 962: ~/.local/share/nvim/lazy/lsp_signature.nvim/lua/lsp_signature/init.lua:938> [signature on insert enter]
<Lua 758: ~/.local/share/nvim/lazy/lsp_signature.nvim/lua/lsp_signature/init.lua:938> [signature on insert enter]
BlinkSnippetsEagerEnter  InsertEnter
*<Lua 990: ~/.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/sources/snippets/builtin.lua:173>
```

Maybe adding an autocmd specifically for that might help?

**Comment by rachartier** [comment]
There is no `InsertEnter` because it works in reverse: when you go into insert mode, the plugin will clear all extmarks created for diagnostics.

When you set `enable_on_insert`, I do not set any autocmd to clear extmarks (as opposed when it's unset), so it should always be displayed. That's why it is strange that it doesn't work!

**Comment by rachartier** [comment]
Just to be 100% sure: did you restart (quit and reopen) Neovim when you added `enable_on_insert` in your config?

**Comment by Torathion** [comment]
It was always set, even since my last issue. Let me clean up my config and upload it to github. Then test around it and break it as much as you like.

**Comment by Torathion** [comment]
Hey, I'm back. Here is my config: [WispVim](https://github.com/Torathion/WispVim)

I've been learning lua for a week now, so don't expect anything to work, lol.

**Comment by rachartier** [comment]
Thanks

I think you should really dig into the documentation of `lazy.nvim`. A lot of things are not compatible/wrong in your config. You should follow the recommended guideline, it will be far easier for you to maintain, and things will not break!

No problem with my plugin, `enable_on_insert` works as expected:
![issue_inline_3](https://github.com/user-attachments/assets/5fdb0f38-079e-49c0-a87a-6d33ace70c1c)

In your file [intellisense.lua](https://github.com/Torathion/WispVim/blob/fec6dbd11e73d3b327a1d28698919fe8764e0e76/wispvim/intellisense.lua#L299) you call `require('tiny-inline-diagnostic').setup()`, except it will be overwritten by `lazy.nvim` with its lazy loading. What you should do in `loadPlugins.lua` is to write this:
```lua
		{
			'rachartier/tiny-inline-diagnostic.nvim',
			event = 'LspAttach',
			priority = 1000,
			opts = {
				preset = 'modern',
				options = {
					throttle = 100,
					enable_on_insert = true,
					multiple_diag_under_cursor = true,
					show_all_diags_on cursorline = true,
					multilines = {
						enabled = true,
						always_show = true,
					},
				},
			},
		},
```

And it will work as expected.

Please, read the lazy.nvim documentation, or take a look at my [nvim dots](https://github.com/rachartier/dotfiles/tree/main/.config/nvim) (I do not use LazyVim, only lazy.nvim). It is not perfect by any means, but it will surely help you.

Have a nice new year eve !

**Comment by Torathion** [comment]
Okay, I'll try to restructure in the next few days. I'll close it for now, but when it's still there, I'll reopen it.
