### ISSUE TITLE
Diagnostics not showing up

### ISSUE THREAD

**Issue by Davidyz** [rachartier/tiny-inline-diagnostic.nvim#9]
Hi, I set up this plugin as follows: 
```lua
{
    "rachartier/tiny-inline-diagnostic.nvim",
    event = { "LspAttach" }, -- tried "VeryLazy" from the README and it didn't help.
    dependencies = { "folke/tokyonight.nvim", "neovim/nvim-lspconfig" },
    init = function()
      vim.diagnostic.config({
        virtual_text = false,
      })
    end,
    main = "tiny-inline-diagnostic",
    cond = utils.no_vscode,
    opts = {},
  }
```
and the diagnostics rarely show up (sometimes they do, mostly not. I wasn't able to identify the reason) when I move the cursor to a location with a diagnostic. It works as intended when I remove `buffer = event.buf` from [here](https://github.com/rachartier/tiny-inline-diagnostic.nvim/blob/83e04d296ee18ba0d44202fc3b706b32cdae7215/lua/tiny-inline-diagnostic/diagnostic.lua#L266) and [here](https://github.com/rachartier/tiny-inline-diagnostic.nvim/blob/83e04d296ee18ba0d44202fc3b706b32cdae7215/lua/tiny-inline-diagnostic/diagnostic.lua#L279). I'm not sure how to further debug. Is this a bug or is there something else in my config that might be messing up with the autocmd?

**Comment by rachartier** [comment]
Hello,

What languages and LSP are you using ? 
Did you try for exemple in Lua? 

Maybe try to do a minimal config (a .lua with only lazy and the plugin, then execute `nvim -U minimal.lua`) to see if the bug is here ?

**Comment by Davidyz** [comment]
I tried lua with `lua_ls` and python with `basedpyright` and `ruff`. The same issue happened in both cases. I also tried manually setting diagnostics without any language servers and it still doesn't work properly.

Here's the minimal `init.lua` used for the testing:
```lua
local diagnostic = {
  {
    lnum = 2,
    col = 0,
    message = "This is a custom diagnostic message.",
    severity = vim.diagnostic.severity.ERROR,
    source = "my_linter",
  },
  {
    lnum = 3,
    col = 0,
    message = "This is a custom diagnostic message.",
    severity = vim.diagnostic.severity.ERROR,
    source = "my_linter",
  },
}

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup(
  {
    {
      "rachartier/tiny-inline-diagnostic.nvim",
      init = function()
        vim.diagnostic.config({
          virtual_text = false,
        })
      end,
      main = "tiny-inline-diagnostic",
      opts = {},
      lazy = false,
    },
  },
  { lazy = false }
)

vim.api.nvim_create_autocmd("CursorHold", {
  callback = function()
    vim.diagnostic.set(vim.api.nvim_create_namespace("test"), 0, diagnostic, {})
  end,
})
```

**Comment by rachartier** [comment]
Hello,

"It's correct that it won't work with this minimal example, as I use an LspAttach autocmd to attach to the correct buffer. If you replace LspAttach in diagnostic.lua with something like BufEnter, it works as intended.

![image](https://github.com/rachartier/tiny-inline-diagnostic.nvim/assets/2057541/03d9f284-fea4-4417-ab0b-52e12359abcd)

I think the problem could be on your side. I use Pyright at work, and I have never had these issues. If you can send me your dotfiles repository, I could check it out!

**Comment by rachartier** [comment]
Can you try to update the plugin ? I think maybe fix #12 can resolves your issue.

**Comment by Davidyz** [comment]
unfortunately it doesn't fix the issue. So far the only way I've found that can fix the problem is to remove `buffer = event.buf` as mentioned earlier in the issue. My current setup is [here](https://github.com/Davidyz/dotfiles/blob/17f0854340f40861002b901386526826f249c292/neovim/lua/plugins/_lazy.lua#L391) using my own fork that implements my fix (or hack) and it actually works as intended.

**Comment by rachartier** [comment]
I don't really know what to say, i'm sorry...
I've clone your config, changed your fork by this repo, and all worked fine with basedpyright:

![image](https://github.com/rachartier/tiny-inline-diagnostic.nvim/assets/2057541/0dda63ff-5583-4b14-bc7e-55980f5645a7)

![image](https://github.com/rachartier/tiny-inline-diagnostic.nvim/assets/2057541/c14cb58a-aee7-43a4-a330-a6382c41c10c)

![image](https://github.com/rachartier/tiny-inline-diagnostic.nvim/assets/2057541/7e42c4f9-155f-47a9-967d-96a6afdbe49f)

**Comment by Davidyz** [comment]
Thanks for your help anyways. I'll close this issue for now since it's not reproducible. I'll come back if I ever figure this out. Thanks.

**Comment by rachartier** [comment]
I'm sorry that I can't help you more... Do not hesitate to tell me if you've found something !

Have a nice day
